#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SWGConnection
@end

@interface SWGConnection : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* ID of user that owns this correlation [optional]
 */
@property(nonatomic) NSNumber* userId;
/* The id for the connector data source for which the connection is connected 
 */
@property(nonatomic) NSNumber* connectorId;
/* Indicates whether a connector is currently connected to a service for a user. [optional]
 */
@property(nonatomic) NSString* connectStatus;
/* Error message if there is a problem with authorizing this connection. [optional]
 */
@property(nonatomic) NSString* connectError;
/* Time at which an update was requested by a user. [optional]
 */
@property(nonatomic) NSDate* updateRequestedAt;
/* Indicates whether a connector is currently updated. [optional]
 */
@property(nonatomic) NSString* updateStatus;
/* Indicates if there was an error during the update. [optional]
 */
@property(nonatomic) NSString* updateError;
/* The time at which the connector was last successfully updated. [optional]
 */
@property(nonatomic) NSDate* lastSuccessfulUpdatedAt;
/* When the record was first created. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* When the record in the database was last updated. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
