#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SWGCorrelation
@end

@interface SWGCorrelation : SWGObject

/*  [optional]
 */
@property(nonatomic) NSNumber* averageDailyLowCause;
/*  [optional]
 */
@property(nonatomic) NSNumber* averageDailyHighCause;
/*  [optional]
 */
@property(nonatomic) NSNumber* averageEffect;
/*  [optional]
 */
@property(nonatomic) NSNumber* averageEffectFollowingHighCause;
/*  [optional]
 */
@property(nonatomic) NSNumber* averageEffectFollowingLowCause;
/*  [optional]
 */
@property(nonatomic) NSString* averageEffectFollowingHighCauseExplanation;
/*  [optional]
 */
@property(nonatomic) NSString* averageEffectFollowingLowCauseExplanation;
/* Average Vote [optional]
 */
@property(nonatomic) NSNumber* averageVote;
/*  [optional]
 */
@property(nonatomic) NSNumber* causalityFactor;
/* Variable name of the cause variable for which the user desires correlations. 
 */
@property(nonatomic) NSString* cause;
/* Variable category of the cause variable. [optional]
 */
@property(nonatomic) NSString* causeVariableCategoryName;
/* Number of changes in the predictor variable (a.k.a the number of experiments) [optional]
 */
@property(nonatomic) NSNumber* causeChanges;
/* The way cause measurements are aggregated [optional]
 */
@property(nonatomic) NSString* causeVariableCombinationOperation;
/*  [optional]
 */
@property(nonatomic) NSString* causeVariableImageUrl;
/* For use in Ionic apps [optional]
 */
@property(nonatomic) NSString* causeVariableIonIcon;
/* Unit of the predictor variable [optional]
 */
@property(nonatomic) NSString* causeUnit;
/* Unit Id of the predictor variable [optional]
 */
@property(nonatomic) NSNumber* causeVariableDefaultUnitId;
/*  [optional]
 */
@property(nonatomic) NSNumber* causeVariableId;
/* Variable name of the cause variable for which the user desires correlations. [optional]
 */
@property(nonatomic) NSString* causeVariableName;
/* Pearson correlation coefficient between cause and effect measurements 
 */
@property(nonatomic) NSNumber* correlationCoefficient;
/* When the record was first created. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* How the data was analyzed [optional]
 */
@property(nonatomic) NSString* dataAnalysis;
/* How the data was obtained [optional]
 */
@property(nonatomic) NSString* dataSources;
/* The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay. 
 */
@property(nonatomic) NSNumber* durationOfAction;
/* Variable name of the effect variable for which the user desires correlations. 
 */
@property(nonatomic) NSString* effect;
/* Variable category of the effect variable. [optional]
 */
@property(nonatomic) NSString* effectVariableCategoryName;
/*  [optional]
 */
@property(nonatomic) NSString* effectVariableImageUrl;
/* For use in Ionic apps [optional]
 */
@property(nonatomic) NSString* effectVariableIonIcon;
/* Magnitude of the effects of a cause indicating whether it's practically meaningful. [optional]
 */
@property(nonatomic) NSString* effectSize;
/* Magnitude of the effects of a cause indicating whether it's practically meaningful. [optional]
 */
@property(nonatomic) NSString* effectVariableId;
/* Variable name of the effect variable for which the user desires correlations. [optional]
 */
@property(nonatomic) NSString* effectVariableName;
/* Illustrates the strength of the relationship [optional]
 */
@property(nonatomic) NSString* gaugeImage;
/* Large image for Facebook [optional]
 */
@property(nonatomic) NSString* imageUrl;
/* Number of points that went into the correlation calculation 
 */
@property(nonatomic) NSNumber* numberOfPairs;
/* The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes. 
 */
@property(nonatomic) NSNumber* onsetDelay;
/* Optimal Pearson Product [optional]
 */
@property(nonatomic) NSNumber* optimalPearsonProduct;
/* original name of the cause. [optional]
 */
@property(nonatomic) NSString* outcomeDataSources;
/* HIGHER Remeron predicts HIGHER Overall Mood [optional]
 */
@property(nonatomic) NSString* predictorExplanation;
/* Mike Sinn [optional]
 */
@property(nonatomic) NSString* principalInvestigator;
/* Value representing the significance of the relationship as a function of crowdsourced insights, predictive strength, data quantity, and data quality [optional]
 */
@property(nonatomic) NSNumber* qmScore;
/* Correlation when cause and effect are reversed. For any causal relationship, the forward correlation should exceed the reverse correlation. [optional]
 */
@property(nonatomic) NSNumber* reverseCorrelation;
/* Using a two-tailed t-test with alpha = 0.05, it was determined that the change... [optional]
 */
@property(nonatomic) NSString* significanceExplanation;
/* A function of the effect size and sample size [optional]
 */
@property(nonatomic) NSString* statisticalSignificance;
/* weak, moderate, strong [optional]
 */
@property(nonatomic) NSString* strengthLevel;
/* These data suggest with a high degree of confidence... [optional]
 */
@property(nonatomic) NSString* studyAbstract;
/* In order to reduce suffering through the advancement of human knowledge... [optional]
 */
@property(nonatomic) NSString* studyBackground;
/* This study is based on data donated by one QuantiModo user... [optional]
 */
@property(nonatomic) NSString* studyDesign;
/* As with any human experiment, it was impossible to control for all potentially confounding variables... [optional]
 */
@property(nonatomic) NSString* studyLimitations;
/* Url for the interactive study within the web app [optional]
 */
@property(nonatomic) NSString* studyLinkDynamic;
/* Url for sharing the study on Facebook [optional]
 */
@property(nonatomic) NSString* studyLinkFacebook;
/* Url for sharing the study on Google+ [optional]
 */
@property(nonatomic) NSString* studyLinkGoogle;
/* Url for sharing the study on Twitter [optional]
 */
@property(nonatomic) NSString* studyLinkTwitter;
/* Url for sharing the statically rendered study on social media [optional]
 */
@property(nonatomic) NSString* studyLinkStatic;
/* The objective of this study is to determine... [optional]
 */
@property(nonatomic) NSString* studyObjective;
/* This analysis suggests that... [optional]
 */
@property(nonatomic) NSString* studyResults;
/* N1 Study HIGHER Remeron predicts HIGHER Overall Mood [optional]
 */
@property(nonatomic) NSString* studyTitle;
/* Time at which correlation was calculated 
 */
@property(nonatomic) NSNumber* timestamp;
/* When the record in the database was last updated. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format. Time zone should be UTC and not local. [optional]
 */
@property(nonatomic) NSDate* updatedAt;
/* User Vote [optional]
 */
@property(nonatomic) NSNumber* userVote;
/* cause value that predicts an above average effect value (in default unit for cause variable) [optional]
 */
@property(nonatomic) NSNumber* valuePredictingHighOutcome;
/* Overall Mood, on average, 34% HIGHER after around 3.98mg Remeron [optional]
 */
@property(nonatomic) NSString* valuePredictingHighOutcomeExplanation;
/* cause value that predicts a below average effect value (in default unit for cause variable) [optional]
 */
@property(nonatomic) NSNumber* valuePredictingLowOutcome;
/* Overall Mood, on average, 4% LOWER after around 0mg Remeron [optional]
 */
@property(nonatomic) NSString* valuePredictingLowOutcomeExplanation;

@end
