#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SWGUserVariableRelationship
@end

@interface SWGUserVariableRelationship : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Our confidence that a consistent predictive relationship exists based on the amount of evidence, reproducibility, and other factors 
 */
@property(nonatomic) NSString* confidenceLevel;
/* A quantitative representation of our confidence that a consistent predictive relationship exists based on the amount of evidence, reproducibility, and other factors 
 */
@property(nonatomic) NSNumber* confidenceScore;
/* Direction is positive if higher predictor values generally precede higher outcome values. Direction is negative if higher predictor values generally precede lower outcome values. 
 */
@property(nonatomic) NSString* direction;
/* The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay. 
 */
@property(nonatomic) NSNumber* durationOfAction;
/* error_message [optional]
 */
@property(nonatomic) NSString* errorMessage;
/* The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes. [optional]
 */
@property(nonatomic) NSNumber* onsetDelay;
/* Variable ID for the outcome variable 
 */
@property(nonatomic) NSNumber* outcomeVariableId;
/* Variable ID for the predictor variable 
 */
@property(nonatomic) NSNumber* predictorVariableId;
/* ID for default unit of the predictor variable 
 */
@property(nonatomic) NSNumber* predictorUnitId;
/* A value representative of the relevance of this predictor relative to other predictors of this outcome.  Usually used for relevancy sorting. 
 */
@property(nonatomic) NSNumber* sinnRank;
/* Can be weak, medium, or strong based on the size of the effect which the predictor appears to have on the outcome relative to other variable relationship strength scores. 
 */
@property(nonatomic) NSString* strengthLevel;
/* A value represented to the size of the effect which the predictor appears to have on the outcome. 
 */
@property(nonatomic) NSNumber* strengthScore;
/* userId [optional]
 */
@property(nonatomic) NSNumber* userId;
/* vote [optional]
 */
@property(nonatomic) NSString* vote;
/* Value for the predictor variable (in it's default unit) which typically precedes an above average outcome value 
 */
@property(nonatomic) NSNumber* valuePredictingHighOutcome;
/* Value for the predictor variable (in it's default unit) which typically precedes a below average outcome value 
 */
@property(nonatomic) NSNumber* valuePredictingLowOutcome;

@end
