#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGAggregatedCorrelation
@end

@interface SWGAggregatedCorrelation : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* correlation 
 */
@property(nonatomic) NSNumber* correlation;
/* cause_id 
 */
@property(nonatomic) NSNumber* causeId;
/* effect_id 
 */
@property(nonatomic) NSNumber* effectId;
/* onset_delay 
 */
@property(nonatomic) NSNumber* onsetDelay;
/* duration_of_action 
 */
@property(nonatomic) NSNumber* durationOfAction;
/* number_of_pairs 
 */
@property(nonatomic) NSNumber* numberOfPairs;
/* value_predicting_high_outcome 
 */
@property(nonatomic) NSNumber* valuePredictingHighOutcome;
/* value_predicting_low_outcome 
 */
@property(nonatomic) NSNumber* valuePredictingLowOutcome;
/* optimal_pearson_product 
 */
@property(nonatomic) NSNumber* optimalPearsonProduct;
/* vote 
 */
@property(nonatomic) NSNumber* vote;
/* number_of_users 
 */
@property(nonatomic) NSNumber* numberOfUsers;
/* number_of_correlations 
 */
@property(nonatomic) NSNumber* numberOfCorrelations;
/* statistical_significance 
 */
@property(nonatomic) NSNumber* statisticalSignificance;
/* cause_unit 
 */
@property(nonatomic) NSString* causeUnit;
/* cause_unit_id 
 */
@property(nonatomic) NSNumber* causeUnitId;
/* cause_changes 
 */
@property(nonatomic) NSNumber* causeChanges;
/* effect_changes 
 */
@property(nonatomic) NSNumber* effectChanges;
/* aggregate_qm_score 
 */
@property(nonatomic) NSNumber* aggregateQmScore;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;
/* status 
 */
@property(nonatomic) NSString* status;
/* error_message 
 */
@property(nonatomic) NSString* errorMessage;
/* last_successful_update_time 
 */
@property(nonatomic) NSDate* lastSuccessfulUpdateTime;
/* reverse_pearson_correlation_coefficient 
 */
@property(nonatomic) NSNumber* reversePearsonCorrelationCoefficient;
/* predictive_pearson_correlation_coefficient 
 */
@property(nonatomic) NSNumber* predictivePearsonCorrelationCoefficient;

@end
