#import <Foundation/Foundation.h>
#import "SWGInlineResponse200.h"
#import "SWGInlineResponse2001.h"
#import "SWGAggregatedCorrelation.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGAggregatedCorrelationApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGAggregatedCorrelationApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGAggregatedCorrelationApi*) sharedAPI;
///
///
/// Get all AggregatedCorrelations
/// Get all AggregatedCorrelations
///
/// @param correlation correlation
/// @param causeId cause_id
/// @param effectId effect_id
/// @param onsetDelay onset_delay
/// @param durationOfAction duration_of_action
/// @param numberOfPairs number_of_pairs
/// @param valuePredictingHighOutcome value_predicting_high_outcome
/// @param valuePredictingLowOutcome value_predicting_low_outcome
/// @param optimalPearsonProduct optimal_pearson_product
/// @param vote vote
/// @param numberOfUsers number_of_users
/// @param numberOfCorrelations number_of_correlations
/// @param statisticalSignificance statistical_significance
/// @param causeUnit cause_unit
/// @param causeUnitId cause_unit_id
/// @param causeChanges cause_changes
/// @param effectChanges effect_changes
/// @param aggregateQmScore aggregate_qm_score
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param status status
/// @param errorMessage error_message
/// @param lastSuccessfulUpdateTime last_successful_update_time
/// @param reversePearsonCorrelationCoefficient reverse_pearson_correlation_coefficient
/// @param predictivePearsonCorrelationCoefficient predictive_pearson_correlation_coefficient
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse200*
-(NSNumber*) aggregatedCorrelationsGetWithCompletionBlock :(NSNumber*) correlation 
     causeId:(NSNumber*) causeId 
     effectId:(NSNumber*) effectId 
     onsetDelay:(NSNumber*) onsetDelay 
     durationOfAction:(NSNumber*) durationOfAction 
     numberOfPairs:(NSNumber*) numberOfPairs 
     valuePredictingHighOutcome:(NSNumber*) valuePredictingHighOutcome 
     valuePredictingLowOutcome:(NSNumber*) valuePredictingLowOutcome 
     optimalPearsonProduct:(NSNumber*) optimalPearsonProduct 
     vote:(NSNumber*) vote 
     numberOfUsers:(NSNumber*) numberOfUsers 
     numberOfCorrelations:(NSNumber*) numberOfCorrelations 
     statisticalSignificance:(NSNumber*) statisticalSignificance 
     causeUnit:(NSString*) causeUnit 
     causeUnitId:(NSNumber*) causeUnitId 
     causeChanges:(NSNumber*) causeChanges 
     effectChanges:(NSNumber*) effectChanges 
     aggregateQmScore:(NSNumber*) aggregateQmScore 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     status:(NSString*) status 
     errorMessage:(NSString*) errorMessage 
     lastSuccessfulUpdateTime:(NSString*) lastSuccessfulUpdateTime 
     reversePearsonCorrelationCoefficient:(NSNumber*) reversePearsonCorrelationCoefficient 
     predictivePearsonCorrelationCoefficient:(NSNumber*) predictivePearsonCorrelationCoefficient 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error))completionBlock;
    


///
///
/// Store AggregatedCorrelation
/// Store AggregatedCorrelation
///
/// @param body AggregatedCorrelation that should be stored
/// 
///
/// @return SWGInlineResponse2001*
-(NSNumber*) aggregatedCorrelationsPostWithCompletionBlock :(SWGAggregatedCorrelation*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2001* output, NSError* error))completionBlock;
    


///
///
/// Get AggregatedCorrelation
/// Get AggregatedCorrelation
///
/// @param _id id of AggregatedCorrelation
/// 
///
/// @return SWGInlineResponse2001*
-(NSNumber*) aggregatedCorrelationsIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2001* output, NSError* error))completionBlock;
    


///
///
/// Update AggregatedCorrelation
/// Update AggregatedCorrelation
///
/// @param _id id of AggregatedCorrelation
/// @param body AggregatedCorrelation that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) aggregatedCorrelationsIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGAggregatedCorrelation*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete AggregatedCorrelation
/// Delete AggregatedCorrelation
///
/// @param _id id of AggregatedCorrelation
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) aggregatedCorrelationsIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
