#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGConversionStep
@end

@interface SWGConversionStep : SWGObject

/* ADD or MULTIPLY 
 */
@property(nonatomic) NSString* operation;
/* This specifies the order of conversion steps starting with 0 
 */
@property(nonatomic) NSNumber* value;

@end
