#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGCorrelation
@end

@interface SWGCorrelation : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Time at which correlation was calculated 
 */
@property(nonatomic) NSNumber* timestamp;
/* ID of user that owns this correlation 
 */
@property(nonatomic) NSNumber* userId;
/* Pearson correlation coefficient between cause and effect measurements 
 */
@property(nonatomic) NSNumber* correlation;
/* variable ID of the cause variable for which the user desires correlations 
 */
@property(nonatomic) NSNumber* causeId;
/* variable ID of the effect variable for which the user desires correlations 
 */
@property(nonatomic) NSNumber* effectId;
/* User estimated or default time after cause measurement before a perceivable effect is observed 
 */
@property(nonatomic) NSNumber* onsetDelay;
/* Time over which the cause is expected to produce a perceivable effect following the onset delay 
 */
@property(nonatomic) NSNumber* durationOfAction;
/* Number of points that went into the correlation calculation 
 */
@property(nonatomic) NSNumber* numberOfPairs;
/* cause value that predicts an above average effect value (in default unit for cause variable) 
 */
@property(nonatomic) NSNumber* valuePredictingHighOutcome;
/* cause value that predicts a below average effect value (in default unit for cause variable) 
 */
@property(nonatomic) NSNumber* valuePredictingLowOutcome;
/* Optimal Pearson Product 
 */
@property(nonatomic) NSNumber* optimalPearsonProduct;
/* Vote 
 */
@property(nonatomic) NSNumber* vote;
/* A function of the effect size and sample size 
 */
@property(nonatomic) NSNumber* statisticalSignificance;
/* Unit of Cause 
 */
@property(nonatomic) NSString* causeUnit;
/* Unit ID of Cause 
 */
@property(nonatomic) NSNumber* causeUnitId;
/* Cause changes 
 */
@property(nonatomic) NSNumber* causeChanges;
/* Effect changes 
 */
@property(nonatomic) NSNumber* effectChanges;
/* QM Score 
 */
@property(nonatomic) NSNumber* qmScore;
/* error 
 */
@property(nonatomic) NSString* error;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;
/* Correlation when cause and effect are reversed. For any causal relationship, the forward correlation should exceed the reverse correlation 
 */
@property(nonatomic) NSNumber* reversePearsonCorrelationCoefficient;
/* Predictive Pearson Correlation Coefficient 
 */
@property(nonatomic) NSNumber* predictivePearsonCorrelationCoefficient;

@end
