#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGCredential
@end

@interface SWGCredential : SWGObject

/* connector_id 
 */
@property(nonatomic) NSNumber* connectorId;
/* attr_key [optional]
 */
@property(nonatomic) NSString* attrKey;
/* attr_value [optional]
 */
@property(nonatomic) NSString* attrValue;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
