#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGConnector
@end

@interface SWGConnector : SWGObject

/* Connector ID number [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Connector lowercase system name 
 */
@property(nonatomic) NSString* name;
/* Connector pretty display name 
 */
@property(nonatomic) NSString* displayName;
/* URL to the image of the connector logo 
 */
@property(nonatomic) NSString* image;
/* URL to a site where one can get this device or application 
 */
@property(nonatomic) NSString* getItUrl;
/* Short description 
 */
@property(nonatomic) NSString* shortDescription;
/* Long description 
 */
@property(nonatomic) NSString* longDescription;
/* enabled 
 */
@property(nonatomic) NSNumber* enabled;
/* oauth 
 */
@property(nonatomic) NSNumber* oauth;

@end
