#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGConnectorInstruction
@end

@interface SWGConnectorInstruction : SWGObject

/* url [optional]
 */
@property(nonatomic) NSString* url;
/* parameters array [optional]
 */
@property(nonatomic) NSArray* /* NSString */ parameters;
/* usePopup [optional]
 */
@property(nonatomic) NSNumber* usePopup;

@end
