#import <Foundation/Foundation.h>
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGConnectApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGConnectApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
///
///
/// Get embeddable connect javascript
/// Get embeddable connect javascript
///
/// @param t User token
/// 
///
/// @return 
-(NSNumber*) v1ConnectJsGetWithCompletionBlock :(NSString*) t 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// Mobile connect page
/// Mobile connect page
///
/// @param t User token
/// 
///
/// @return 
-(NSNumber*) v1ConnectMobileGetWithCompletionBlock :(NSString*) t 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;



@end
