#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGConnection
@end

@interface SWGConnection : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* user_id [optional]
 */
@property(nonatomic) NSNumber* userId;
/* connector_id 
 */
@property(nonatomic) NSNumber* connectorId;
/* connect_status [optional]
 */
@property(nonatomic) NSString* connectStatus;
/* connect_error [optional]
 */
@property(nonatomic) NSString* connectError;
/* update_requested_at [optional]
 */
@property(nonatomic) NSDate* updateRequestedAt;
/* update_status [optional]
 */
@property(nonatomic) NSString* updateStatus;
/* update_error [optional]
 */
@property(nonatomic) NSString* updateError;
/* last_successful_updated_at [optional]
 */
@property(nonatomic) NSDate* lastSuccessfulUpdatedAt;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
