#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGHumanTime
@end

@interface SWGHumanTime : SWGObject

/* date time [optional]
 */
@property(nonatomic) NSString* date;

@property(nonatomic) NSNumber* timezoneType;
/* timezone of date time [optional]
 */
@property(nonatomic) NSString* timezone;

@end
