#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGUpdate.h"


@protocol SWGInlineResponse20020
@end

@interface SWGInlineResponse20020 : SWGObject


@property(nonatomic) SWGUpdate* data;

@property(nonatomic) NSNumber* success;

@end
