#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMeasurement.h"


@protocol SWGInlineResponse20011
@end

@interface SWGInlineResponse20011 : SWGObject


@property(nonatomic) NSArray<SWGMeasurement>* data;

@property(nonatomic) NSNumber* success;

@end
