#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGUpdate.h"


@protocol SWGInlineResponse20019
@end

@interface SWGInlineResponse20019 : SWGObject


@property(nonatomic) NSArray<SWGUpdate>* data;

@property(nonatomic) NSNumber* success;

@end
