#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGCredential.h"


@protocol SWGInlineResponse2009
@end

@interface SWGInlineResponse2009 : SWGObject


@property(nonatomic) NSArray<SWGCredential>* data;

@property(nonatomic) NSNumber* success;

@end
