#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGConnection.h"


@protocol SWGInlineResponse2004
@end

@interface SWGInlineResponse2004 : SWGObject


@property(nonatomic) SWGConnection* data;

@property(nonatomic) NSNumber* success;

@end
