#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGSource.h"


@protocol SWGInlineResponse20014
@end

@interface SWGInlineResponse20014 : SWGObject


@property(nonatomic) SWGSource* data;

@property(nonatomic) NSNumber* success;

@end
