#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGCorrelation.h"


@protocol SWGInlineResponse2007
@end

@interface SWGInlineResponse2007 : SWGObject


@property(nonatomic) NSArray<SWGCorrelation>* data;

@property(nonatomic) NSNumber* success;

@end
