#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGConnection.h"


@protocol SWGInlineResponse2003
@end

@interface SWGInlineResponse2003 : SWGObject


@property(nonatomic) NSArray<SWGConnection>* data;

@property(nonatomic) NSNumber* success;

@end
