#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGInlineResponse2002
@end

@interface SWGInlineResponse2002 : SWGObject


@property(nonatomic) NSString* data;

@property(nonatomic) NSNumber* success;

@end
