#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGVariableCategory.h"


@protocol SWGInlineResponse20023
@end

@interface SWGInlineResponse20023 : SWGObject


@property(nonatomic) NSArray<SWGVariableCategory>* data;

@property(nonatomic) NSNumber* success;

@end
