#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGVariableUserSource.h"


@protocol SWGInlineResponse20026
@end

@interface SWGInlineResponse20026 : SWGObject


@property(nonatomic) SWGVariableUserSource* data;

@property(nonatomic) NSNumber* success;

@end
