#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGCorrelation.h"


@protocol SWGInlineResponse2008
@end

@interface SWGInlineResponse2008 : SWGObject


@property(nonatomic) SWGCorrelation* data;

@property(nonatomic) NSNumber* success;

@end
