#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGUnitCategory.h"


@protocol SWGInlineResponse20016
@end

@interface SWGInlineResponse20016 : SWGObject


@property(nonatomic) SWGUnitCategory* data;

@property(nonatomic) NSNumber* success;

@end
