#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGVariableUserSource.h"


@protocol SWGInlineResponse20025
@end

@interface SWGInlineResponse20025 : SWGObject


@property(nonatomic) NSArray<SWGVariableUserSource>* data;

@property(nonatomic) NSNumber* success;

@end
