#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGUnit.h"


@protocol SWGInlineResponse20017
@end

@interface SWGInlineResponse20017 : SWGObject


@property(nonatomic) NSArray<SWGUnit>* data;

@property(nonatomic) NSNumber* success;

@end
