#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGConnector.h"


@protocol SWGInlineResponse2006
@end

@interface SWGInlineResponse2006 : SWGObject


@property(nonatomic) SWGConnector* data;

@property(nonatomic) NSNumber* success;

@end
