#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGVariable.h"


@protocol SWGInlineResponse20028
@end

@interface SWGInlineResponse20028 : SWGObject


@property(nonatomic) SWGVariable* data;

@property(nonatomic) NSNumber* success;

@end
