#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGVote.h"


@protocol SWGInlineResponse20030
@end

@interface SWGInlineResponse20030 : SWGObject


@property(nonatomic) SWGVote* data;

@property(nonatomic) NSNumber* success;

@end
