#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGAggregatedCorrelation.h"


@protocol SWGInlineResponse2001
@end

@interface SWGInlineResponse2001 : SWGObject


@property(nonatomic) SWGAggregatedCorrelation* data;

@property(nonatomic) NSNumber* success;

@end
