#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGUserVariable.h"


@protocol SWGInlineResponse20022
@end

@interface SWGInlineResponse20022 : SWGObject


@property(nonatomic) SWGUserVariable* data;

@property(nonatomic) NSNumber* success;

@end
