#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGMeasurementDelete
@end

@interface SWGMeasurementDelete : SWGObject

/* Variable id of the measurement to be deleted 
 */
@property(nonatomic) NSNumber* variableId;
/* Start time of the measurement to be deleted 
 */
@property(nonatomic) NSNumber* startTime;

@end
