#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMeasurementValue.h"


@protocol SWGMeasurementPost
@end

@interface SWGMeasurementPost : SWGObject

/* variable_id 
 */
@property(nonatomic) NSNumber* variableId;
/* source_id 
 */
@property(nonatomic) NSNumber* sourceId;
/* unit_id 
 */
@property(nonatomic) NSNumber* unitId;
/* measurements 
 */
@property(nonatomic) NSArray<SWGMeasurementValue>* measurements;

@end
