#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGMeasurementValue
@end

@interface SWGMeasurementValue : SWGObject

/* start_time 
 */
@property(nonatomic) NSNumber* startTime;
/* value 
 */
@property(nonatomic) NSNumber* value;

@end
