#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGValueObject.h"


@protocol SWGMeasurementSet
@end

@interface SWGMeasurementSet : SWGObject

/* Array of timestamps, values, and optional notes 
 */
@property(nonatomic) NSArray<SWGValueObject>* measurements;
/* ORIGINAL name of the variable for which we are creating the measurement records 
 */
@property(nonatomic) NSString* name;
/* Name of the application or device used to record the measurement values 
 */
@property(nonatomic) NSString* source;
/* Variable category name [optional]
 */
@property(nonatomic) NSString* category;
/* Way to aggregate measurements over time. Options are \"MEAN\" or \"SUM\".  SUM should be used for things like minutes of exercise.  If you use MEAN for exercise, then a person might exercise more minutes in one day but add separate measurements that were smaller.  So when we are doing correlational analysis, we would think that the person exercised less that day even though they exercised more.  Conversely, we must use MEAN for things such as ratings which cannot be SUMMED. [optional]
 */
@property(nonatomic) NSString* combinationOperation;
/* Unit of measurement 
 */
@property(nonatomic) NSString* unit;

@end
