#import <Foundation/Foundation.h>
#import "SWGInlineResponse20011.h"
#import "SWGMeasurementPost.h"
#import "SWGInlineResponse20012.h"
#import "SWGInlineResponse2002.h"
#import "SWGMeasurement.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGMeasurementApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGMeasurementApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGMeasurementApi*) sharedAPI;
///
///
/// Get all Measurements
/// Get all Measurements
///
/// @param userId user_id
/// @param clientId client_id
/// @param connectorId connector_id
/// @param variableId variable_id
/// @param startTime start_time
/// @param value value
/// @param originalValue original_value
/// @param duration duration
/// @param note note
/// @param latitude latitude
/// @param longitude longitude
/// @param location location
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param error error
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20011*
-(NSNumber*) measurementsGetWithCompletionBlock :(NSNumber*) userId 
     clientId:(NSString*) clientId 
     connectorId:(NSNumber*) connectorId 
     variableId:(NSNumber*) variableId 
     startTime:(NSNumber*) startTime 
     value:(NSNumber*) value 
     originalValue:(NSNumber*) originalValue 
     duration:(NSNumber*) duration 
     note:(NSString*) note 
     latitude:(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     location:(NSString*) location 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     error:(NSString*) error 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20011* output, NSError* error))completionBlock;
    


///
///
/// Store Measurement
/// Store Measurement
///
/// @param body Measurement that should be stored
/// 
///
/// @return SWGInlineResponse20011*
-(NSNumber*) measurementsPostWithCompletionBlock :(SWGMeasurementPost*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20011* output, NSError* error))completionBlock;
    


///
///
/// Get Measurements CSV
/// Get Measurements CSV
///
/// 
///
/// @return NSURL*
-(NSNumber*) measurementsCsvGetWithCompletionBlock :
    (void (^)(NSURL* output, NSError* error))completionBlock;
    


///
///
/// Post Request for Measurements CSV
/// Post Request for Measurements CSV
///
/// 
///
/// @return NSNumber*
-(NSNumber*) measurementsRequestCsvPostWithCompletionBlock :
    (void (^)(NSNumber* output, NSError* error))completionBlock;
    


///
///
/// Get Measurement
/// Get Measurement
///
/// @param _id id of Measurement
/// 
///
/// @return SWGInlineResponse20012*
-(NSNumber*) measurementsIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse20012* output, NSError* error))completionBlock;
    


///
///
/// Update Measurement
/// Update Measurement
///
/// @param _id id of Measurement
/// @param body Measurement that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) measurementsIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGMeasurement*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete Measurement
/// Delete Measurement
///
/// @param _id id of Measurement
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) measurementsIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
