#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGMeasurement
@end

@interface SWGMeasurement : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* ID of user that owns this measurement [optional]
 */
@property(nonatomic) NSNumber* userId;
/* client_id [optional]
 */
@property(nonatomic) NSString* clientId;
/* Connector ID [optional]
 */
@property(nonatomic) NSNumber* connectorId;
/* ID of the variable for which we are creating the measurement records 
 */
@property(nonatomic) NSNumber* variableId;
/* Application or device used to record the measurement values 
 */
@property(nonatomic) NSNumber* sourceId;
/* Start Time for the measurement event in ISO 8601 
 */
@property(nonatomic) NSNumber* startTime;
/* Converted measurement value in requested unit 
 */
@property(nonatomic) NSNumber* value;
/* Unit ID of measurement as requested in GET request 
 */
@property(nonatomic) NSNumber* unitId;
/* Original value [optional]
 */
@property(nonatomic) NSNumber* originalValue;
/* Unit ID of measurement as originally submitted [optional]
 */
@property(nonatomic) NSNumber* originalUnitId;
/* duration of measurement in seconds [optional]
 */
@property(nonatomic) NSNumber* duration;
/* Note of measurement [optional]
 */
@property(nonatomic) NSString* note;
/* latitude [optional]
 */
@property(nonatomic) NSNumber* latitude;
/* longitude [optional]
 */
@property(nonatomic) NSNumber* longitude;
/* location [optional]
 */
@property(nonatomic) NSString* location;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;
/* error [optional]
 */
@property(nonatomic) NSString* error;

@end
