#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPostVote
@end

@interface SWGPostVote : SWGObject

/* Cause variable name 
 */
@property(nonatomic) NSString* cause;
/* Effect variable name 
 */
@property(nonatomic) NSString* effect;
/* Vote: 0 (for implausible) or 1 (for plausible) 
 */
@property(nonatomic) NSNumber* vote;

@end
