#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPairs
@end

@interface SWGPairs : SWGObject

/* Category name 
 */
@property(nonatomic) NSString* name;

@end
