#import <Foundation/Foundation.h>
#import "SWGInlineResponse20013.h"
#import "SWGSource.h"
#import "SWGInlineResponse20014.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGSourceApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGSourceApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGSourceApi*) sharedAPI;
///
///
/// Get all Sources
/// Get all Sources
///
/// @param clientId client_id
/// @param name name
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20013*
-(NSNumber*) sourcesGetWithCompletionBlock :(NSString*) clientId 
     name:(NSString*) name 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20013* output, NSError* error))completionBlock;
    


///
///
/// Store Source
/// Store Source
///
/// @param body Source that should be stored
/// 
///
/// @return SWGInlineResponse20014*
-(NSNumber*) sourcesPostWithCompletionBlock :(SWGSource*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20014* output, NSError* error))completionBlock;
    


///
///
/// Get Source
/// Get Source
///
/// @param _id id of Source
/// 
///
/// @return SWGInlineResponse20014*
-(NSNumber*) sourcesIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse20014* output, NSError* error))completionBlock;
    


///
///
/// Update Source
/// Update Source
///
/// @param _id id of Source
/// @param body Source that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) sourcesIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGSource*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete Source
/// Delete Source
///
/// @param _id id of Source
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) sourcesIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
