#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGTrackingReminderPending
@end

@interface SWGTrackingReminderPending : SWGObject

/* id for the specific PENDING tracking remidner 
 */
@property(nonatomic) NSNumber* _id;
/* id for the repeating tracking remidner 
 */
@property(nonatomic) NSNumber* trackingReminderId;
/* clientId [optional]
 */
@property(nonatomic) NSString* clientId;
/* ID of User [optional]
 */
@property(nonatomic) NSNumber* userId;
/* Id for the variable to be tracked [optional]
 */
@property(nonatomic) NSNumber* variableId;
/* ISO 8601 timestamp for the specific time the variable should be tracked in UTC.  This will be used for the measurement startTime if the track endpoint is used. [optional]
 */
@property(nonatomic) NSDate* pendingReminderTime;
/* Default value to use for the measurement when tracking [optional]
 */
@property(nonatomic) NSNumber* defaultValue;
/* String identifier for the sound to accompany the reminder [optional]
 */
@property(nonatomic) NSString* reminderSound;
/* True if the reminders should appear as a popup notification [optional]
 */
@property(nonatomic) NSNumber* popUp;
/* True if the reminders should be delivered via SMS [optional]
 */
@property(nonatomic) NSNumber* sms;
/* True if the reminders should be delivered via email [optional]
 */
@property(nonatomic) NSNumber* email;
/* True if the reminders should appear in the notification bar [optional]
 */
@property(nonatomic) NSNumber* notificationBar;
/* When the record in the database was last updated. Use ISO 8601 datetime format. Time zone should be UTC and not local. [optional]
 */
@property(nonatomic) NSDate* updatedAt;
/* Name of the variable to be used when sending measurements [optional]
 */
@property(nonatomic) NSString* variableName;
/* Name of the variable category to be used when sending measurements [optional]
 */
@property(nonatomic) NSString* variableCategoryName;
/* Abbreviated name of the unit to be used when sending measurements [optional]
 */
@property(nonatomic) NSString* abbreviatedUnitName;
/* The way multiple measurements are aggregated over time [optional]
 */
@property(nonatomic) NSString* combinationOperation;

@end
