#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGTrackingReminderPendingTrack
@end

@interface SWGTrackingReminderPendingTrack : SWGObject

/* Id of the PENDING reminder to be tracked 
 */
@property(nonatomic) NSNumber* _id;

@end
