#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGTrackingReminder
@end

@interface SWGTrackingReminder : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* clientId [optional]
 */
@property(nonatomic) NSString* clientId;
/* ID of User [optional]
 */
@property(nonatomic) NSNumber* userId;
/* Id for the variable to be tracked 
 */
@property(nonatomic) NSNumber* variableId;
/* Default value to use for the measurement when tracking [optional]
 */
@property(nonatomic) NSNumber* defaultValue;
/* Earliest time of day at which reminders should appear [optional]
 */
@property(nonatomic) NSString* reminderStartTime;
/* Latest time of day at which reminders should appear [optional]
 */
@property(nonatomic) NSString* reminderEndTime;
/* String identifier for the sound to accompany the reminder [optional]
 */
@property(nonatomic) NSString* reminderSound;
/* Number of seconds between one reminder and the next [optional]
 */
@property(nonatomic) NSNumber* reminderFrequency;
/* True if the reminders should appear as a popup notification [optional]
 */
@property(nonatomic) NSNumber* popUp;
/* True if the reminders should be delivered via SMS [optional]
 */
@property(nonatomic) NSNumber* sms;
/* True if the reminders should be delivered via email [optional]
 */
@property(nonatomic) NSNumber* email;
/* True if the reminders should appear in the notification bar [optional]
 */
@property(nonatomic) NSNumber* notificationBar;
/* ISO 8601 timestamp for the last time a reminder was sent [optional]
 */
@property(nonatomic) NSDate* lastReminded;
/* ISO 8601 timestamp for the last time a measurement was received for this user and variable [optional]
 */
@property(nonatomic) NSDate* lastTracked;
/* Specific first time of day that the user should be reminded to track in HH:MM:SS format [optional]
 */
@property(nonatomic) NSString* firstDailyReminderTime;
/* Specific second time of day that the user should be reminded to track in HH:MM:SS format [optional]
 */
@property(nonatomic) NSString* secondDailyReminderTime;
/* Specific third time of day that the user should be reminded to track in HH:MM:SS format [optional]
 */
@property(nonatomic) NSString* thirdDailyReminderTime;
/* Earliest date on which the user should be reminded to track in YYYY-MM-DD format [optional]
 */
@property(nonatomic) NSDate* startTrackingDate;
/* Latest date on which the user should be reminded to track in YYYY-MM-DD format [optional]
 */
@property(nonatomic) NSDate* stopTrackingDate;
/* When the record in the database was last updated. Use ISO 8601 datetime format. Time zone should be UTC and not local. [optional]
 */
@property(nonatomic) NSDate* updatedAt;
/* Name of the variable to be used when sending measurements [optional]
 */
@property(nonatomic) NSString* variableName;
/* Name of the variable category to be used when sending measurements [optional]
 */
@property(nonatomic) NSString* variableCategoryName;
/* Abbreviated name of the unit to be used when sending measurements [optional]
 */
@property(nonatomic) NSString* abbreviatedUnitName;
/* The way multiple measurements are aggregated over time [optional]
 */
@property(nonatomic) NSString* combinationOperation;

@end
