#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUnit
@end

@interface SWGUnit : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* client_id [optional]
 */
@property(nonatomic) NSString* clientId;
/* Unit name 
 */
@property(nonatomic) NSString* name;
/* Unit abbreviation 
 */
@property(nonatomic) NSString* abbreviatedName;
/* Unit category ID 
 */
@property(nonatomic) NSNumber* categoryId;
/* Unit minimum value [optional]
 */
@property(nonatomic) NSNumber* minimumValue;
/* Unit maximum value [optional]
 */
@property(nonatomic) NSNumber* maximumValue;
/* updated [optional]
 */
@property(nonatomic) NSNumber* updated;
/* ID of default unit [optional]
 */
@property(nonatomic) NSNumber* defaultUnitId;
/* Value multiplied to [optional]
 */
@property(nonatomic) NSNumber* multiply;
/* Value which should be added to convert to default unit [optional]
 */
@property(nonatomic) NSNumber* add;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
