#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserTokenSuccessfulResponseInnerUserField
@end

@interface SWGUserTokenSuccessfulResponseInnerUserField : SWGObject

/* WordPress user ID 
 */
@property(nonatomic) NSNumber* _id;
/* User token 
 */
@property(nonatomic) NSString* accessToken;

@end
