#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserVariable
@end

@interface SWGUserVariable : SWGObject

/* ID of the parent variable if this variable has any parent [optional]
 */
@property(nonatomic) NSNumber* parentId;
/* client_id [optional]
 */
@property(nonatomic) NSString* clientId;
/* ID of variable 
 */
@property(nonatomic) NSNumber* variableId;
/* ID of unit to use for this variable [optional]
 */
@property(nonatomic) NSNumber* defaultUnitId;
/* Minimum reasonable value for this variable (uses default unit) [optional]
 */
@property(nonatomic) NSNumber* minimumAllowedValue;
/* Maximum reasonable value for this variable (uses default unit) [optional]
 */
@property(nonatomic) NSNumber* maximumAllowedValue;
/* Value for replacing null measurements [optional]
 */
@property(nonatomic) NSNumber* fillingValue;
/* The Variable this Variable should be joined with. If the variable is joined with some other variable then it is not shown to user in the list of variables [optional]
 */
@property(nonatomic) NSNumber* joinWith;
/* How long it takes for a measurement in this variable to take effect [optional]
 */
@property(nonatomic) NSNumber* onsetDelay;
/* Estimated duration of time following the onset delay in which a stimulus produces a perceivable effect [optional]
 */
@property(nonatomic) NSNumber* durationOfAction;
/* ID of variable category [optional]
 */
@property(nonatomic) NSNumber* variableCategoryId;
/* updated [optional]
 */
@property(nonatomic) NSNumber* updated;
/* Is variable public [optional]
 */
@property(nonatomic) NSNumber* public;
/* A value of 1 indicates that this variable is generally a cause in a causal relationship.  An example of a causeOnly variable would be a variable such as Cloud Cover which would generally not be influenced by the behaviour of the user [optional]
 */
@property(nonatomic) NSNumber* causeOnly;
/* 0 -> No filling, 1 -> Use filling-value [optional]
 */
@property(nonatomic) NSString* fillingType;
/* Number of measurements [optional]
 */
@property(nonatomic) NSNumber* numberOfMeasurements;
/* Number of processed measurements [optional]
 */
@property(nonatomic) NSNumber* numberOfProcessedMeasurements;
/* Number of measurements at last analysis [optional]
 */
@property(nonatomic) NSNumber* measurementsAtLastAnalysis;
/* ID of last Unit [optional]
 */
@property(nonatomic) NSNumber* lastUnitId;
/* ID of last original Unit [optional]
 */
@property(nonatomic) NSNumber* lastOriginalUnitId;
/* Last Value [optional]
 */
@property(nonatomic) NSNumber* lastValue;
/* Last original value which is stored [optional]
 */
@property(nonatomic) NSNumber* lastOriginalValue;
/* ID of last source [optional]
 */
@property(nonatomic) NSNumber* lastSourceId;
/* Number of correlations for this variable [optional]
 */
@property(nonatomic) NSNumber* numberOfCorrelations;
/* status [optional]
 */
@property(nonatomic) NSString* status;
/* error_message [optional]
 */
@property(nonatomic) NSString* errorMessage;
/* When this variable or its settings were last updated [optional]
 */
@property(nonatomic) NSDate* lastSuccessfulUpdateTime;
/* Standard deviation [optional]
 */
@property(nonatomic) NSNumber* standardDeviation;
/* Variance [optional]
 */
@property(nonatomic) NSNumber* variance;
/* Minimum recorded daily value of this variable [optional]
 */
@property(nonatomic) NSNumber* minimumRecordedDailyValue;
/* Maximum recorded daily value of this variable [optional]
 */
@property(nonatomic) NSNumber* maximumRecordedDailyValue;
/* Mean [optional]
 */
@property(nonatomic) NSNumber* mean;
/* Median [optional]
 */
@property(nonatomic) NSNumber* median;
/* Most common Unit ID [optional]
 */
@property(nonatomic) NSNumber* mostCommonUnitId;
/* Most common value [optional]
 */
@property(nonatomic) NSNumber* mostCommonValue;
/* Number of unique daily values [optional]
 */
@property(nonatomic) NSNumber* numberOfUniqueDailyValues;
/* Number of changes [optional]
 */
@property(nonatomic) NSNumber* numberOfChanges;
/* Skewness [optional]
 */
@property(nonatomic) NSNumber* skewness;
/* Kurtosis [optional]
 */
@property(nonatomic) NSNumber* kurtosis;
/* Latitude [optional]
 */
@property(nonatomic) NSNumber* latitude;
/* Longitude [optional]
 */
@property(nonatomic) NSNumber* longitude;
/* Location [optional]
 */
@property(nonatomic) NSString* location;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;
/* Outcome variables (those with `outcome` == 1) are variables for which a human would generally want to identify the influencing factors.  These include symptoms of illness, physique, mood, cognitive performance, etc.  Generally correlation calculations are only performed on outcome variables [optional]
 */
@property(nonatomic) NSNumber* outcome;
/* Comma-separated list of source names to limit variables to those sources [optional]
 */
@property(nonatomic) NSString* sources;
/* Earliest source time [optional]
 */
@property(nonatomic) NSNumber* earliestSourceTime;
/* Latest source time [optional]
 */
@property(nonatomic) NSNumber* latestSourceTime;
/* Earliest measurement time [optional]
 */
@property(nonatomic) NSNumber* earliestMeasurementTime;
/* Latest measurement time [optional]
 */
@property(nonatomic) NSNumber* latestMeasurementTime;
/* Earliest filling time [optional]
 */
@property(nonatomic) NSNumber* earliestFillingTime;
/* Latest filling time [optional]
 */
@property(nonatomic) NSNumber* latestFillingTime;

@end
