#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUpdate
@end

@interface SWGUpdate : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* user_id 
 */
@property(nonatomic) NSNumber* userId;
/* connector_id 
 */
@property(nonatomic) NSNumber* connectorId;
/* number_of_measurements 
 */
@property(nonatomic) NSNumber* numberOfMeasurements;
/* success 
 */
@property(nonatomic) NSNumber* success;
/* message 
 */
@property(nonatomic) NSString* message;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
