#import <Foundation/Foundation.h>
#import "SWGInlineResponse20015.h"
#import "SWGUnitCategory.h"
#import "SWGInlineResponse20016.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGUnitCategoryApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGUnitCategoryApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGUnitCategoryApi*) sharedAPI;
///
///
/// Get all UnitCategories
/// Get all UnitCategories
///
/// @param name name
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20015*
-(NSNumber*) unitCategoriesGetWithCompletionBlock :(NSString*) name 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20015* output, NSError* error))completionBlock;
    


///
///
/// Store UnitCategory
/// Store UnitCategory
///
/// @param body UnitCategory that should be stored
/// 
///
/// @return SWGInlineResponse20016*
-(NSNumber*) unitCategoriesPostWithCompletionBlock :(SWGUnitCategory*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20016* output, NSError* error))completionBlock;
    


///
///
/// Get UnitCategory
/// Get UnitCategory
///
/// @param _id id of UnitCategory
/// 
///
/// @return SWGInlineResponse20016*
-(NSNumber*) unitCategoriesIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse20016* output, NSError* error))completionBlock;
    


///
///
/// Update UnitCategory
/// Update UnitCategory
///
/// @param _id id of UnitCategory
/// @param body UnitCategory that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) unitCategoriesIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGUnitCategory*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete UnitCategory
/// Delete UnitCategory
///
/// @param _id id of UnitCategory
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) unitCategoriesIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
