#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserTokenRequestInnerUserField
@end

@interface SWGUserTokenRequestInnerUserField : SWGObject

/* WordPress user ID [optional]
 */
@property(nonatomic) NSNumber* _id;

@end
