#import <Foundation/Foundation.h>
#import "SWGInlineResponse20017.h"
#import "SWGInlineResponse20018.h"
#import "SWGUnit.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGUnitApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGUnitApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGUnitApi*) sharedAPI;
///
///
/// Get all Units
/// Get all Units
///
/// @param clientId client_id
/// @param name name
/// @param abbreviatedName abbreviated_name
/// @param categoryId category_id
/// @param minimumValue minimum_value
/// @param maximumValue maximum_value
/// @param updated updated
/// @param multiply multiply
/// @param add add
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20017*
-(NSNumber*) unitsGetWithCompletionBlock :(NSString*) clientId 
     name:(NSString*) name 
     abbreviatedName:(NSString*) abbreviatedName 
     categoryId:(NSNumber*) categoryId 
     minimumValue:(NSNumber*) minimumValue 
     maximumValue:(NSNumber*) maximumValue 
     updated:(NSNumber*) updated 
     multiply:(NSNumber*) multiply 
     add:(NSNumber*) add 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20017* output, NSError* error))completionBlock;
    


///
///
/// Store Unit
/// Store Unit
///
/// @param body Unit that should be stored
/// 
///
/// @return SWGInlineResponse20018*
-(NSNumber*) unitsPostWithCompletionBlock :(SWGUnit*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20018* output, NSError* error))completionBlock;
    


///
///
/// Get Unit
/// Get Unit
///
/// @param _id id of Unit
/// 
///
/// @return SWGInlineResponse20018*
-(NSNumber*) unitsIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse20018* output, NSError* error))completionBlock;
    


///
///
/// Update Unit
/// Update Unit
///
/// @param _id id of Unit
/// @param body Unit that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) unitsIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGUnit*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete Unit
/// Delete Unit
///
/// @param _id id of Unit
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) unitsIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
