#import <Foundation/Foundation.h>
#import "SWGInlineResponse20021.h"
#import "SWGInlineResponse20022.h"
#import "SWGUserVariable.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGUserVariableApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGUserVariableApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGUserVariableApi*) sharedAPI;
///
///
/// Get all UserVariables
/// Get all UserVariables
///
/// @param clientId client_id
/// @param variableId variable_id
/// @param defaultUnitId default_unit_id
/// @param minimumAllowedValue minimum_allowed_value
/// @param maximumAllowedValue maximum_allowed_value
/// @param fillingValue filling_value
/// @param joinWith join_with
/// @param onsetDelay onset_delay
/// @param durationOfAction duration_of_action
/// @param variableCategoryId variable_category_id
/// @param updated updated
/// @param public public
/// @param causeOnly cause_only
/// @param fillingType filling_type
/// @param numberOfMeasurements number_of_measurements
/// @param numberOfProcessedMeasurements number_of_processed_measurements
/// @param measurementsAtLastAnalysis measurements_at_last_analysis
/// @param lastUnitId last_unit_id
/// @param lastOriginalUnitId last_original_unit_id
/// @param lastOriginalValue last_original_value
/// @param lastValue last_value
/// @param lastSourceId last_source_id
/// @param numberOfCorrelations number_of_correlations
/// @param status status
/// @param errorMessage error_message
/// @param lastSuccessfulUpdateTime last_successful_update_time
/// @param standardDeviation standard_deviation
/// @param variance variance
/// @param minimumRecordedDailyValue minimum_recorded_daily_value
/// @param maximumRecordedDailyValue maximum_recorded_daily_value
/// @param mean mean
/// @param median median
/// @param mostCommonUnitId most_common_unit_id
/// @param mostCommonValue most_common_value
/// @param numberOfUniqueDailyValues number_of_unique_daily_values
/// @param numberOfChanges number_of_changes
/// @param skewness skewness
/// @param kurtosis kurtosis
/// @param latitude latitude
/// @param longitude longitude
/// @param location location
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param outcome outcome
/// @param sources sources
/// @param earliestSourceTime earliest_source_time
/// @param latestSourceTime latest_source_time
/// @param earliestMeasurementTime earliest_measurement_time
/// @param latestMeasurementTime latest_measurement_time
/// @param earliestFillingTime earliest_filling_time
/// @param latestFillingTime latest_filling_time
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20021*
-(NSNumber*) userVariablesGetWithCompletionBlock :(NSString*) clientId 
     variableId:(NSNumber*) variableId 
     defaultUnitId:(NSNumber*) defaultUnitId 
     minimumAllowedValue:(NSNumber*) minimumAllowedValue 
     maximumAllowedValue:(NSNumber*) maximumAllowedValue 
     fillingValue:(NSNumber*) fillingValue 
     joinWith:(NSNumber*) joinWith 
     onsetDelay:(NSNumber*) onsetDelay 
     durationOfAction:(NSNumber*) durationOfAction 
     variableCategoryId:(NSNumber*) variableCategoryId 
     updated:(NSNumber*) updated 
     public:(NSNumber*) public 
     causeOnly:(NSNumber*) causeOnly 
     fillingType:(NSString*) fillingType 
     numberOfMeasurements:(NSNumber*) numberOfMeasurements 
     numberOfProcessedMeasurements:(NSNumber*) numberOfProcessedMeasurements 
     measurementsAtLastAnalysis:(NSNumber*) measurementsAtLastAnalysis 
     lastUnitId:(NSNumber*) lastUnitId 
     lastOriginalUnitId:(NSNumber*) lastOriginalUnitId 
     lastOriginalValue:(NSNumber*) lastOriginalValue 
     lastValue:(NSNumber*) lastValue 
     lastSourceId:(NSNumber*) lastSourceId 
     numberOfCorrelations:(NSNumber*) numberOfCorrelations 
     status:(NSString*) status 
     errorMessage:(NSString*) errorMessage 
     lastSuccessfulUpdateTime:(NSString*) lastSuccessfulUpdateTime 
     standardDeviation:(NSNumber*) standardDeviation 
     variance:(NSNumber*) variance 
     minimumRecordedDailyValue:(NSNumber*) minimumRecordedDailyValue 
     maximumRecordedDailyValue:(NSNumber*) maximumRecordedDailyValue 
     mean:(NSNumber*) mean 
     median:(NSNumber*) median 
     mostCommonUnitId:(NSNumber*) mostCommonUnitId 
     mostCommonValue:(NSNumber*) mostCommonValue 
     numberOfUniqueDailyValues:(NSNumber*) numberOfUniqueDailyValues 
     numberOfChanges:(NSNumber*) numberOfChanges 
     skewness:(NSNumber*) skewness 
     kurtosis:(NSNumber*) kurtosis 
     latitude:(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     location:(NSString*) location 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     outcome:(NSNumber*) outcome 
     sources:(NSString*) sources 
     earliestSourceTime:(NSNumber*) earliestSourceTime 
     latestSourceTime:(NSNumber*) latestSourceTime 
     earliestMeasurementTime:(NSNumber*) earliestMeasurementTime 
     latestMeasurementTime:(NSNumber*) latestMeasurementTime 
     earliestFillingTime:(NSNumber*) earliestFillingTime 
     latestFillingTime:(NSNumber*) latestFillingTime 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20021* output, NSError* error))completionBlock;
    


///
///
/// Store UserVariable
/// Store UserVariable
///
/// @param body UserVariable that should be stored
/// 
///
/// @return SWGInlineResponse20022*
-(NSNumber*) userVariablesPostWithCompletionBlock :(SWGUserVariable*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20022* output, NSError* error))completionBlock;
    


///
///
/// Get UserVariable
/// Get UserVariable
///
/// @param _id id of UserVariable
/// 
///
/// @return SWGInlineResponse20022*
-(NSNumber*) userVariablesIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse20022* output, NSError* error))completionBlock;
    


///
///
/// Update UserVariable
/// Update UserVariable
///
/// @param _id id of UserVariable
/// @param body UserVariable that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) userVariablesIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGUserVariable*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete UserVariable
/// Delete UserVariable
///
/// @param _id id of UserVariable
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) userVariablesIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
