#import <Foundation/Foundation.h>
#import "SWGInlineResponse20019.h"
#import "SWGUpdate.h"
#import "SWGInlineResponse20020.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGUpdateApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGUpdateApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGUpdateApi*) sharedAPI;
///
///
/// Get all Updates
/// Get all Updates
///
/// @param userId user_id
/// @param connectorId connector_id
/// @param numberOfMeasurements number_of_measurements
/// @param success success
/// @param message message
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20019*
-(NSNumber*) updatesGetWithCompletionBlock :(NSNumber*) userId 
     connectorId:(NSNumber*) connectorId 
     numberOfMeasurements:(NSNumber*) numberOfMeasurements 
     success:(NSNumber*) success 
     message:(NSString*) message 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20019* output, NSError* error))completionBlock;
    


///
///
/// Store Update
/// Store Update
///
/// @param body Update that should be stored
/// 
///
/// @return SWGInlineResponse20020*
-(NSNumber*) updatesPostWithCompletionBlock :(SWGUpdate*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20020* output, NSError* error))completionBlock;
    


///
///
/// Get Update
/// Get Update
///
/// @param _id id of Update
/// 
///
/// @return SWGInlineResponse20020*
-(NSNumber*) updatesIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse20020* output, NSError* error))completionBlock;
    


///
///
/// Update Update
/// Update Update
///
/// @param _id id of Update
/// @param body Update that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) updatesIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGUpdate*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete Update
/// Delete Update
///
/// @param _id id of Update
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) updatesIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
