#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserTokenFailedResponse
@end

@interface SWGUserTokenFailedResponse : SWGObject

/* Status code 
 */
@property(nonatomic) NSNumber* code;
/* Message 
 */
@property(nonatomic) NSString* message;

@property(nonatomic) NSNumber* success;

@end
