#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserVariables
@end

@interface SWGUserVariables : SWGObject

/* User ID 
 */
@property(nonatomic) NSNumber* user;
/* Variable DISPLAY name 
 */
@property(nonatomic) NSString* variable;
/* Estimated duration of time following the onset delay in which a stimulus produces a perceivable effect 
 */
@property(nonatomic) NSNumber* durationOfAction;
/* fillingValue 
 */
@property(nonatomic) NSNumber* fillingValue;
/* joinWith 
 */
@property(nonatomic) NSString* joinWith;
/* maximumAllowedValue 
 */
@property(nonatomic) NSNumber* maximumAllowedValue;
/* minimumAllowedValue 
 */
@property(nonatomic) NSNumber* minimumAllowedValue;
/* name 
 */
@property(nonatomic) NSString* name;
/* onsetDelay 
 */
@property(nonatomic) NSNumber* onsetDelay;
/* unit 
 */
@property(nonatomic) NSString* unit;

@end
