#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUnitCategory
@end

@interface SWGUnitCategory : SWGObject

/* Category name 
 */
@property(nonatomic) NSString* name;

@end
