#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserVariables
@end

@interface SWGUserVariables : SWGObject

/* User ID 
 */
@property(nonatomic) NSNumber* user;
/* Common variable id 
 */
@property(nonatomic) NSNumber* variableId;
/* Estimated duration of time following the onset delay in which a stimulus produces a perceivable effect [optional]
 */
@property(nonatomic) NSNumber* durationOfAction;
/* fillingValue [optional]
 */
@property(nonatomic) NSNumber* fillingValue;
/* joinWith [optional]
 */
@property(nonatomic) NSString* joinWith;
/* maximumAllowedValue [optional]
 */
@property(nonatomic) NSNumber* maximumAllowedValue;
/* minimumAllowedValue [optional]
 */
@property(nonatomic) NSNumber* minimumAllowedValue;
/* onsetDelay [optional]
 */
@property(nonatomic) NSNumber* onsetDelay;
/* Earliest measurement startTime that should be used in analysis in ISO format [optional]
 */
@property(nonatomic) NSString* experimentStartTime;
/* Latest measurement startTime that should be used in analysis in ISO format [optional]
 */
@property(nonatomic) NSString* experimentEndTime;

@end
