#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUnitConversion
@end

@interface SWGUnitConversion : SWGObject

/* unit_id 
 */
@property(nonatomic) NSNumber* unitId;
/* step in the conversion process 
 */
@property(nonatomic) NSNumber* stepNumber;
/* 0 is add and 1 is multiply 
 */
@property(nonatomic) NSNumber* operation;
/* number used in the operation 
 */
@property(nonatomic) NSNumber* value;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
