#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserTag
@end

@interface SWGUserTag : SWGObject

/* This is the id of the variable being tagged with an ingredient or something. 
 */
@property(nonatomic) NSNumber* taggedVariableId;
/* This is the id of the ingredient variable whose value is determined based on the value of the tagged variable. 
 */
@property(nonatomic) NSNumber* tagVariableId;
/* Number by which we multiply the tagged variable value to obtain the tag variable (ingredient) value 
 */
@property(nonatomic) NSNumber* conversionFactor;

@end
