#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGConversionStep.h"


@protocol SWGUnit
@end

@interface SWGUnit : SWGObject

/* Unit name 
 */
@property(nonatomic) NSString* name;
/* Unit abbreviation 
 */
@property(nonatomic) NSString* abbreviatedName;
/* Unit category 
 */
@property(nonatomic) NSString* category;
/* The smallest acceptable value for measurements using this unit [optional]
 */
@property(nonatomic) NSNumber* minimumValue;
/* The largest acceptable value for measurements using this unit [optional]
 */
@property(nonatomic) NSNumber* maximumValue;
/* Conversion steps list 
 */
@property(nonatomic) NSArray<SWGConversionStep>* conversionSteps;

@end
