#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUnitCategory
@end

@interface SWGUnitCategory : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Unit category name 
 */
@property(nonatomic) NSString* name;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
