#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGUserTokenSuccessfulResponseInnerUserField.h"


@protocol SWGUserTokenSuccessfulResponse
@end

@interface SWGUserTokenSuccessfulResponse : SWGObject

/* Status code 
 */
@property(nonatomic) NSNumber* code;
/* Message 
 */
@property(nonatomic) NSString* message;

@property(nonatomic) SWGUserTokenSuccessfulResponseInnerUserField* user;

@end
