#import <Foundation/Foundation.h>
#import "SWGInlineResponse20025.h"
#import "SWGVariableUserSource.h"
#import "SWGInlineResponse20026.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGVariableUserSourceApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGVariableUserSourceApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGVariableUserSourceApi*) sharedAPI;
///
///
/// Get all VariableUserSources
/// Get all VariableUserSources
///
/// @param variableId variable_id
/// @param userId user_id
/// @param timestamp timestamp
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20025*
-(NSNumber*) variableUserSourcesGetWithCompletionBlock :(NSNumber*) variableId 
     userId:(NSNumber*) userId 
     timestamp:(NSNumber*) timestamp 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20025* output, NSError* error))completionBlock;
    


///
///
/// Store VariableUserSource
/// Store VariableUserSource
///
/// @param body VariableUserSource that should be stored
/// 
///
/// @return SWGInlineResponse20026*
-(NSNumber*) variableUserSourcesPostWithCompletionBlock :(SWGVariableUserSource*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20026* output, NSError* error))completionBlock;
    


///
///
/// Get VariableUserSource
/// Get VariableUserSource
///
/// @param _id id of VariableUserSource
/// @param sourceId source id of VariableUserSource
/// 
///
/// @return SWGInlineResponse20026*
-(NSNumber*) variableUserSourcesIdGetWithCompletionBlock :(NSNumber*) _id 
     sourceId:(NSNumber*) sourceId 
    
    completionHandler: (void (^)(SWGInlineResponse20026* output, NSError* error))completionBlock;
    


///
///
/// Update VariableUserSource
/// Update VariableUserSource
///
/// @param _id variable_id of VariableUserSource
/// @param sourceId source id of VariableUserSource
/// @param body VariableUserSource that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) variableUserSourcesIdPutWithCompletionBlock :(NSNumber*) _id 
     sourceId:(NSNumber*) sourceId 
     body:(SWGVariableUserSource*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete VariableUserSource
/// Delete VariableUserSource
///
/// @param _id variable_id of VariableUserSource
/// @param sourceId source id of VariableUserSource
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) variableUserSourcesIdDeleteWithCompletionBlock :(NSNumber*) _id 
     sourceId:(NSNumber*) sourceId 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
