#import <Foundation/Foundation.h>
#import "SWGPostVote.h"
#import "SWGCommonResponse.h"
#import "SWGVoteDelete.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGVotesApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGVotesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGVotesApi*) sharedAPI;
///
///
/// Post or update vote
/// This is to enable users to indicate their opinion on the plausibility of a causal relationship between a treatment and outcome. QuantiModo incorporates crowd-sourced plausibility estimations into their algorithm. This is done allowing user to indicate their view of the plausibility of each relationship with thumbs up/down buttons placed next to each prediction.
///
/// @param body Contains the cause variable, effect variable, and vote value.
/// @param accessToken User&#39;s OAuth2 access token
/// 
///
/// @return SWGCommonResponse*
-(NSNumber*) v1VotesPostWithCompletionBlock :(SWGPostVote*) body 
     accessToken:(NSString*) accessToken 
    
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error))completionBlock;
    


///
///
/// Delete vote
/// Delete previously posted vote
///
/// @param body The cause and effect variable names for the predictor vote to be deleted.
/// 
///
/// @return SWGCommonResponse*
-(NSNumber*) v1VotesDeletePostWithCompletionBlock :(SWGVoteDelete*) body 
    
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error))completionBlock;
    



@end
