#import <Foundation/Foundation.h>
#import "SWGInlineResponse20029.h"
#import "SWGInlineResponse20030.h"
#import "SWGVote.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGVoteApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGVoteApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGVoteApi*) sharedAPI;
///
///
/// Get all Votes
/// Get all Votes
///
/// @param clientId client_id
/// @param userId user_id
/// @param causeId cause_id
/// @param effectId effect_id
/// @param value value
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20029*
-(NSNumber*) votesGetWithCompletionBlock :(NSString*) clientId 
     userId:(NSNumber*) userId 
     causeId:(NSNumber*) causeId 
     effectId:(NSNumber*) effectId 
     value:(NSNumber*) value 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20029* output, NSError* error))completionBlock;
    


///
///
/// Store Vote
/// Store Vote
///
/// @param body Vote that should be stored
/// 
///
/// @return SWGInlineResponse20030*
-(NSNumber*) votesPostWithCompletionBlock :(SWGVote*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20030* output, NSError* error))completionBlock;
    


///
///
/// Get Vote
/// Get Vote
///
/// @param _id id of Vote
/// 
///
/// @return SWGInlineResponse20030*
-(NSNumber*) votesIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse20030* output, NSError* error))completionBlock;
    


///
///
/// Update Vote
/// Update Vote
///
/// @param _id id of Vote
/// @param body Vote that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) votesIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGVote*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete Vote
/// Delete Vote
///
/// @param _id id of Vote
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) votesIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
