#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGVote
@end

@interface SWGVote : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* client_id 
 */
@property(nonatomic) NSString* clientId;
/* ID of User 
 */
@property(nonatomic) NSNumber* userId;
/* ID of cause variable 
 */
@property(nonatomic) NSNumber* causeId;
/* ID of effect variable 
 */
@property(nonatomic) NSNumber* effectId;
/* Value of Vote 
 */
@property(nonatomic) NSNumber* value;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
