#import <Foundation/Foundation.h>
#import "SWGInlineResponse20027.h"
#import "SWGVariable.h"
#import "SWGInlineResponse20028.h"
#import "SWGInlineResponse2002.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGVariableApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGVariableApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGVariableApi*) sharedAPI;
///
///
/// Get all Variables
/// Get all Variables
///
/// @param _id id
/// @param clientId client_id
/// @param parentId parent_id
/// @param name name
/// @param variableCategoryId variable_category_id
/// @param defaultUnitId default_unit_id
/// @param combinationOperation combination_operation
/// @param fillingValue filling_value
/// @param maximumAllowedValue maximum_allowed_value
/// @param minimumAllowedValue minimum_allowed_value
/// @param onsetDelay onset_delay
/// @param durationOfAction duration_of_action
/// @param public public
/// @param causeOnly cause_only
/// @param mostCommonValue most_common_value
/// @param mostCommonUnitId most_common_unit_id
/// @param standardDeviation standard_deviation
/// @param variance variance
/// @param mean mean
/// @param median median
/// @param numberOfMeasurements number_of_measurements
/// @param numberOfUniqueValues number_of_unique_values
/// @param skewness skewness
/// @param kurtosis kurtosis
/// @param latitude latitude
/// @param longitude longitude
/// @param location location
/// @param status status
/// @param errorMessage error_message
/// @param lastSuccessfulUpdateTime last_successful_update_time
/// @param createdAt created_at
/// @param updatedAt updated_at
/// @param productUrl product_url
/// @param imageUrl image_url
/// @param price price
/// @param numberOfUserVariables number_of_user_variables
/// @param outcome outcome
/// @param minimumRecordedValue minimum_recorded_value
/// @param maximumRecordedValue maximum_recorded_value
/// @param limit limit
/// @param offset offset
/// @param sort sort
/// 
///
/// @return SWGInlineResponse20027*
-(NSNumber*) variablesGetWithCompletionBlock :(NSNumber*) _id 
     clientId:(NSString*) clientId 
     parentId:(NSNumber*) parentId 
     name:(NSString*) name 
     variableCategoryId:(NSNumber*) variableCategoryId 
     defaultUnitId:(NSNumber*) defaultUnitId 
     combinationOperation:(NSString*) combinationOperation 
     fillingValue:(NSNumber*) fillingValue 
     maximumAllowedValue:(NSNumber*) maximumAllowedValue 
     minimumAllowedValue:(NSNumber*) minimumAllowedValue 
     onsetDelay:(NSNumber*) onsetDelay 
     durationOfAction:(NSNumber*) durationOfAction 
     public:(NSNumber*) public 
     causeOnly:(NSNumber*) causeOnly 
     mostCommonValue:(NSNumber*) mostCommonValue 
     mostCommonUnitId:(NSNumber*) mostCommonUnitId 
     standardDeviation:(NSNumber*) standardDeviation 
     variance:(NSNumber*) variance 
     mean:(NSNumber*) mean 
     median:(NSNumber*) median 
     numberOfMeasurements:(NSNumber*) numberOfMeasurements 
     numberOfUniqueValues:(NSNumber*) numberOfUniqueValues 
     skewness:(NSNumber*) skewness 
     kurtosis:(NSNumber*) kurtosis 
     latitude:(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     location:(NSString*) location 
     status:(NSString*) status 
     errorMessage:(NSString*) errorMessage 
     lastSuccessfulUpdateTime:(NSString*) lastSuccessfulUpdateTime 
     createdAt:(NSString*) createdAt 
     updatedAt:(NSString*) updatedAt 
     productUrl:(NSString*) productUrl 
     imageUrl:(NSString*) imageUrl 
     price:(NSNumber*) price 
     numberOfUserVariables:(NSNumber*) numberOfUserVariables 
     outcome:(NSNumber*) outcome 
     minimumRecordedValue:(NSNumber*) minimumRecordedValue 
     maximumRecordedValue:(NSNumber*) maximumRecordedValue 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     sort:(NSString*) sort 
    
    completionHandler: (void (^)(SWGInlineResponse20027* output, NSError* error))completionBlock;
    


///
///
/// Store Variable
/// Store Variable
///
/// @param body Variable that should be stored
/// 
///
/// @return SWGInlineResponse20028*
-(NSNumber*) variablesPostWithCompletionBlock :(SWGVariable*) body 
    
    completionHandler: (void (^)(SWGInlineResponse20028* output, NSError* error))completionBlock;
    


///
///
/// Get Variable
/// Get Variable
///
/// @param _id id of Variable
/// 
///
/// @return SWGInlineResponse20028*
-(NSNumber*) variablesIdGetWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse20028* output, NSError* error))completionBlock;
    


///
///
/// Update Variable
/// Update Variable
///
/// @param _id id of Variable
/// @param body Variable that should be updated
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) variablesIdPutWithCompletionBlock :(NSNumber*) _id 
     body:(SWGVariable*) body 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    


///
///
/// Delete Variable
/// Delete Variable
///
/// @param _id id of Variable
/// 
///
/// @return SWGInlineResponse2002*
-(NSNumber*) variablesIdDeleteWithCompletionBlock :(NSNumber*) _id 
    
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error))completionBlock;
    



@end
