#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGValueObject
@end

@interface SWGValueObject : SWGObject

/* Timestamp for the measurement event in epoch time (unixtime) 
 */
@property(nonatomic) NSNumber* timestamp;
/* Measurement value 
 */
@property(nonatomic) NSNumber* value;
/* Optional note to include with the measurement [optional]
 */
@property(nonatomic) NSString* note;

@end
