#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGVariable
@end

@interface SWGVariable : SWGObject

/* id [optional]
 */
@property(nonatomic) NSNumber* _id;
/* client_id [optional]
 */
@property(nonatomic) NSString* clientId;
/* parent_id [optional]
 */
@property(nonatomic) NSNumber* parentId;
/* Name of the variable 
 */
@property(nonatomic) NSString* name;
/* Category of the variable 
 */
@property(nonatomic) NSNumber* variableCategoryId;
/* ID of the default unit of measurement to use for this variable 
 */
@property(nonatomic) NSNumber* defaultUnitId;
/* How to combine values of this variable (for instance, to see a summary of the values over a month) 0 for sum OR 1 for mean [optional]
 */
@property(nonatomic) NSString* combinationOperation;
/* filling_value [optional]
 */
@property(nonatomic) NSNumber* fillingValue;
/* maximum_allowed_value [optional]
 */
@property(nonatomic) NSNumber* maximumAllowedValue;
/* minimum_allowed_value [optional]
 */
@property(nonatomic) NSNumber* minimumAllowedValue;
/* onset_delay [optional]
 */
@property(nonatomic) NSNumber* onsetDelay;
/* duration_of_action [optional]
 */
@property(nonatomic) NSNumber* durationOfAction;
/* public [optional]
 */
@property(nonatomic) NSNumber* public;
/* cause_only [optional]
 */
@property(nonatomic) NSNumber* causeOnly;
/* most_common_value [optional]
 */
@property(nonatomic) NSNumber* mostCommonValue;
/* most_common_unit_id [optional]
 */
@property(nonatomic) NSNumber* mostCommonUnitId;
/* standard_deviation [optional]
 */
@property(nonatomic) NSNumber* standardDeviation;
/* variance [optional]
 */
@property(nonatomic) NSNumber* variance;
/* mean [optional]
 */
@property(nonatomic) NSNumber* mean;
/* median [optional]
 */
@property(nonatomic) NSNumber* median;
/* number_of_measurements [optional]
 */
@property(nonatomic) NSNumber* numberOfMeasurements;
/* number_of_unique_values [optional]
 */
@property(nonatomic) NSNumber* numberOfUniqueValues;
/* skewness [optional]
 */
@property(nonatomic) NSNumber* skewness;
/* kurtosis [optional]
 */
@property(nonatomic) NSNumber* kurtosis;
/* status [optional]
 */
@property(nonatomic) NSString* status;
/* error_message [optional]
 */
@property(nonatomic) NSString* errorMessage;
/* last_successful_update_time [optional]
 */
@property(nonatomic) NSDate* lastSuccessfulUpdateTime;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;
/* product_url [optional]
 */
@property(nonatomic) NSString* productUrl;
/* image_url [optional]
 */
@property(nonatomic) NSString* imageUrl;
/* price [optional]
 */
@property(nonatomic) NSNumber* price;
/* number_of_user_variables [optional]
 */
@property(nonatomic) NSNumber* numberOfUserVariables;
/* outcome [optional]
 */
@property(nonatomic) NSNumber* outcome;
/* minimum_recorded_value [optional]
 */
@property(nonatomic) NSNumber* minimumRecordedValue;
/* maximum_recorded_value [optional]
 */
@property(nonatomic) NSNumber* maximumRecordedValue;

@end
