#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGVariableUserSource
@end

@interface SWGVariableUserSource : SWGObject

/* ID of User [optional]
 */
@property(nonatomic) NSNumber* userId;
/* ID of variable 
 */
@property(nonatomic) NSNumber* variableId;
/* ID of source 
 */
@property(nonatomic) NSNumber* sourceId;
/* Time that this measurement occurred Uses epoch minute (epoch time divided by 60) 
 */
@property(nonatomic) NSNumber* timestamp;
/* Earliest measurement time 
 */
@property(nonatomic) NSNumber* earliestMeasurementTime;
/* Latest measurement time 
 */
@property(nonatomic) NSNumber* latestMeasurementTime;
/* created_at [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* updated_at [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
