#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGVariableNew
@end

@interface SWGVariableNew : SWGObject

/* User-defined variable display name. 
 */
@property(nonatomic) NSString* name;
/* Variable category like Mood, Sleep, Physical Activity, Treatment, Symptom, etc. 
 */
@property(nonatomic) NSString* category;
/* Abbreviated name of the default unit for the variable 
 */
@property(nonatomic) NSString* unit;
/* Way to aggregate measurements over time. Options are \"MEAN\" or \"SUM\".  SUM should be used for things like minutes of exercise.  If you use MEAN for exercise, then a person might exercise more minutes in one day but add separate measurements that were smaller.  So when we are doing correlational analysis, we would think that the person exercised less that day even though they exercised more.  Conversely, we must use MEAN for things such as ratings which cannot be SUMMED. 
 */
@property(nonatomic) NSString* combinationOperation;
/* Parent 
 */
@property(nonatomic) NSString* parent;

@end
