#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGVoteDelete
@end

@interface SWGVoteDelete : SWGObject

/* Cause variable name for the correlation to which the vote pertains 
 */
@property(nonatomic) NSString* cause;
/* Effect variable name for the correlation to which the vote pertains 
 */
@property(nonatomic) NSString* effect;

@end
