#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGVariable.h"


@protocol SWGVariable
@end

@interface SWGVariable : SWGObject

/* Variable ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* User-defined variable display name. 
 */
@property(nonatomic) NSString* name;
/* Name used when the variable was originally created in the `variables` table. 
 */
@property(nonatomic) NSString* originalName;
/* Variable category like Mood, Sleep, Physical Activity, Treatment, Symptom, etc. 
 */
@property(nonatomic) NSString* category;
/* Abbreviated name of the default unit for the variable 
 */
@property(nonatomic) NSString* unit;
/* Comma-separated list of source names to limit variables to those sources 
 */
@property(nonatomic) NSString* sources;
/* Minimum reasonable value for this variable (uses default unit) 
 */
@property(nonatomic) NSNumber* minimumValue;
/* Maximum reasonable value for this variable (uses default unit) 
 */
@property(nonatomic) NSNumber* maximumValue;
/* How to aggregate measurements over time. 
 */
@property(nonatomic) NSString* combinationOperation;
/* Value for replacing null measurements 
 */
@property(nonatomic) NSNumber* fillingValue;
/* The Variable this Variable should be joined with. If the variable is joined with some other variable then it is not shown to user in the list of variables. 
 */
@property(nonatomic) NSString* joinWith;
/* Array of Variables that are joined with this Variable 
 */
@property(nonatomic) NSArray<SWGVariable>* joinedVariables;
/* Id of the parent variable if this variable has any parent 
 */
@property(nonatomic) NSNumber* parent;
/* Array of Variables that are sub variables to this Variable 
 */
@property(nonatomic) NSArray<SWGVariable>* subVariables;
/* How long it takes for a measurement in this variable to take effect 
 */
@property(nonatomic) NSNumber* onsetDelay;
/* How long the effect of a measurement in this variable lasts 
 */
@property(nonatomic) NSNumber* durationOfAction;
/* Earliest measurement time 
 */
@property(nonatomic) NSNumber* earliestMeasurementTime;
/* Latest measurement time 
 */
@property(nonatomic) NSNumber* latestMeasurementTime;
/* When this variable or its settings were last updated 
 */
@property(nonatomic) NSNumber* updated;
/* A value of 1 indicates that this variable is generally a cause in a causal relationship.  An example of a causeOnly variable would be a variable such as Cloud Cover which would generally not be influenced by the behaviour of the user. 
 */
@property(nonatomic) NSNumber* causeOnly;
/* Number of correlations 
 */
@property(nonatomic) NSNumber* numberOfCorrelations;
/* Outcome variables (those with `outcome` == 1) are variables for which a human would generally want to identify the influencing factors.  These include symptoms of illness, physique, mood, cognitive performance, etc.  Generally correlation calculations are only performed on outcome variables. 
 */
@property(nonatomic) NSNumber* outcome;
/* The number of measurements that a given user had for this variable the last time a correlation calculation was performed. Generally correlation values are only updated once the current number of measurements for a variable is more than 10% greater than the measurementsAtLastAnalysis.  This avoids a computationally-demanding recalculation when there's not enough new data to make a significant difference in the correlation. 
 */
@property(nonatomic) NSNumber* measurementsAtLastAnalysis;
/* Number of measurements 
 */
@property(nonatomic) NSNumber* numberOfMeasurements;
/* Last unit 
 */
@property(nonatomic) NSNumber* lastUnit;
/* Last value 
 */
@property(nonatomic) NSNumber* lastValue;
/* Most common value 
 */
@property(nonatomic) NSNumber* mostCommonValue;
/* Most common unit 
 */
@property(nonatomic) NSNumber* mostCommonUnit;
/* Last source 
 */
@property(nonatomic) NSNumber* lastSource;

@end
