#import <Foundation/Foundation.h>
#import "SWGCommonResponse.h"
#import "SWGCorrelation.h"
#import "SWGJsonErrorResponse.h"
#import "SWGPostCorrelation.h"
#import "SWGPostVote.h"
#import "SWGVoteDelete.h"
#import "SWGApi.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGCorrelationsApi: NSObject <SWGApi>

extern NSString* kSWGCorrelationsApiErrorDomain;
extern NSInteger kSWGCorrelationsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Get aggregated correlations
/// Get correlations based on the anonymized aggregate data from all QuantiModo users.
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param effect Variable name of the effect variable for which the user desires correlations (optional)
/// @param cause Variable name of the cause variable for which the user desires correlations (optional)
/// @param correlationCoefficient Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action (optional)
/// @param onsetDelay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes. (optional)
/// @param durationOfAction The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay. (optional)
/// @param updatedAt The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request. (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
/// @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
/// @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCorrelation>*
-(NSNumber*) v1AggregatedCorrelationsGetWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    effect: (NSString*) effect
    cause: (NSString*) cause
    correlationCoefficient: (NSString*) correlationCoefficient
    onsetDelay: (NSString*) onsetDelay
    durationOfAction: (NSString*) durationOfAction
    updatedAt: (NSString*) updatedAt
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSNumber*) sort
    outcomesOfInterest: (NSNumber*) outcomesOfInterest
    completionHandler: (void (^)(NSArray<SWGCorrelation>* output, NSError* error)) handler;


/// Store or Update a Correlation
/// Add correlation
///
/// @param body Provides correlation data
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:400 message:"Bad request",
///  code:401 message:"Not Authenticated"
///
/// @return 
-(NSNumber*) v1AggregatedCorrelationsPostWithBody: (SWGPostCorrelation*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSError* error)) handler;


/// Get correlations
/// Get correlations based on data from a single user.
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param effect Variable name of the effect variable for which the user desires correlations (optional)
/// @param cause Variable name of the cause variable for which the user desires correlations (optional)
/// @param correlationCoefficient Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action (optional)
/// @param onsetDelay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes. (optional)
/// @param durationOfAction The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay. (optional)
/// @param updatedAt The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request. (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
/// @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
/// @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCorrelation>*
-(NSNumber*) v1CorrelationsGetWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    effect: (NSString*) effect
    cause: (NSString*) cause
    correlationCoefficient: (NSString*) correlationCoefficient
    onsetDelay: (NSString*) onsetDelay
    durationOfAction: (NSString*) durationOfAction
    updatedAt: (NSString*) updatedAt
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSNumber*) sort
    outcomesOfInterest: (NSNumber*) outcomesOfInterest
    completionHandler: (void (^)(NSArray<SWGCorrelation>* output, NSError* error)) handler;


/// Search user correlations for a given cause
/// Returns average of all correlations and votes for all user cause variables for a given cause. If parameter \"include_public\" is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
///
/// @param organizationId Organization ID
/// @param userId2 User id
/// @param variableName Effect variable name
/// @param organizationToken Organization access token
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param includePublic Include public correlations, Can be \&quot;1\&quot; or empty. (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCorrelation>*
-(NSNumber*) v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameCausesGetWithOrganizationId: (NSNumber*) organizationId
    userId2: (NSNumber*) userId2
    variableName: (NSString*) variableName
    organizationToken: (NSString*) organizationToken
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    includePublic: (NSString*) includePublic
    completionHandler: (void (^)(NSArray<SWGCorrelation>* output, NSError* error)) handler;


/// Search user correlations for a given cause
/// Returns average of all correlations and votes for all user cause variables for a given effect. If parameter \"include_public\" is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
///
/// @param organizationId Organization ID
/// @param userId2 User id
/// @param variableName Cause variable name
/// @param organizationToken Organization access token
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param includePublic Include public correlations, Can be \&quot;1\&quot; or empty. (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCommonResponse>*
-(NSNumber*) v1OrganizationsOrganizationIdUsersUserIdVariablesVariableNameEffectsGetWithOrganizationId: (NSNumber*) organizationId
    userId2: (NSNumber*) userId2
    variableName: (NSString*) variableName
    organizationToken: (NSString*) organizationToken
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    includePublic: (NSString*) includePublic
    completionHandler: (void (^)(NSArray<SWGCommonResponse>* output, NSError* error)) handler;


/// Get average correlations for variables containing search term
/// Returns the average correlations from all users for all public variables that contain the characters in the search query. Returns average of all users public variable correlations with a specified cause or effect.
///
/// @param search Name of the variable that you want to know the causes or effects of.
/// @param effectOrCause Setting this to effect indicates that the searched variable is the effect and that the causes of this variable should be returned. cause indicates that the searched variable is the cause and the effects should be returned.
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param outcomesOfInterest Only include correlations for which the effect is an outcome of interest for the user (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCorrelation>*
-(NSNumber*) v1PublicCorrelationsSearchSearchGetWithSearch: (NSString*) search
    effectOrCause: (NSString*) effectOrCause
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    outcomesOfInterest: (NSNumber*) outcomesOfInterest
    completionHandler: (void (^)(NSArray<SWGCorrelation>* output, NSError* error)) handler;


/// Search user correlations for a given effect
/// Returns average of all correlations and votes for all user cause variables for a given effect
///
/// @param variableName Effect variable name
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCorrelation>*
-(NSNumber*) v1VariablesVariableNameCausesGetWithVariableName: (NSString*) variableName
    completionHandler: (void (^)(NSArray<SWGCorrelation>* output, NSError* error)) handler;


/// Search user correlations for a given cause
/// Returns average of all correlations and votes for all user effect variables for a given cause
///
/// @param variableName Cause variable name
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param correlationCoefficient You can use this to get effects with correlations greater than or less than 0 (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCorrelation>*
-(NSNumber*) v1VariablesVariableNameEffectsGetWithVariableName: (NSString*) variableName
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    correlationCoefficient: (NSString*) correlationCoefficient
    completionHandler: (void (^)(NSArray<SWGCorrelation>* output, NSError* error)) handler;


/// Search public correlations for a given effect
/// Returns average of all correlations and votes for all public cause variables for a given effect
///
/// @param variableName Effect variable name
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param correlationCoefficient You can use this to get causes with correlations greater than or less than 0 (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCorrelation>*
-(NSNumber*) v1VariablesVariableNamePublicCausesGetWithVariableName: (NSString*) variableName
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    correlationCoefficient: (NSString*) correlationCoefficient
    completionHandler: (void (^)(NSArray<SWGCorrelation>* output, NSError* error)) handler;


/// Search public correlations for a given cause
/// Returns average of all correlations and votes for all public cause variables for a given cause
///
/// @param variableName Cause variable name
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGCorrelation>*
-(NSNumber*) v1VariablesVariableNamePublicEffectsGetWithVariableName: (NSString*) variableName
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSArray<SWGCorrelation>* output, NSError* error)) handler;


/// Delete vote
/// Delete previously posted vote
///
/// @param body The cause and effect variable names for the predictor vote to be deleted.
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1VotesDeletePostWithBody: (SWGVoteDelete*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;


/// Post or update vote
/// This is to enable users to indicate their opinion on the plausibility of a causal relationship between a treatment and outcome. QuantiModo incorporates crowd-sourced plausibility estimations into their algorithm. This is done allowing user to indicate their view of the plausibility of each relationship with thumbs up/down buttons placed next to each prediction.
///
/// @param body Contains the cause variable, effect variable, and vote value.
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1VotesPostWithBody: (SWGPostVote*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;



@end
