#import <Foundation/Foundation.h>
#import "SWGCommonResponse.h"
#import "SWGMeasurement.h"
#import "SWGMeasurementDelete.h"
#import "SWGMeasurementRange.h"
#import "SWGMeasurementSet.h"
#import "SWGMeasurementSource.h"
#import "SWGMeasurementUpdate.h"
#import "SWGApi.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGMeasurementsApi: NSObject <SWGApi>

extern NSString* kSWGMeasurementsApiErrorDomain;
extern NSInteger kSWGMeasurementsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Get measurement sources
/// Returns a list of all the apps from which measurement data is obtained.
///
/// 
///  code:200 message:"Successful operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGMeasurementSource*
-(NSNumber*) v1MeasurementSourcesGetWithCompletionHandler: 
    (void (^)(SWGMeasurementSource* output, NSError* error)) handler;


/// Add a data source
/// Add a life-tracking app or device to the QuantiModo list of data sources.
///
/// @param body An array of names of data sources you want to add.
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:401 message:"Not Authenticated"
///
/// @return 
-(NSNumber*) v1MeasurementSourcesPostWithBody: (SWGMeasurementSource*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSError* error)) handler;


/// Get daily measurements for this user
/// Measurements are any value that can be recorded like daily steps, a mood rating, or apples eaten. Supported filter parameters:<ul><li><b>value</b> - Value of measurement</li><li><b>updatedAt</b> - The time that this measurement was created or last updated in the UTC format \"YYYY-MM-DDThh:mm:ss\"</li></ul>
///
/// @param variableName Name of the variable you want measurements for
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param unitAbbreviatedName The unit your want the measurements in (optional)
/// @param startTime The lower limit of measurements returned (UTC Iso8601 \&quot;YYYY-MM-DDThh:mm:ss\&quot; format) (optional)
/// @param endTime The upper limit of measurements returned (UTC Iso8601 \&quot;YYYY-MM-DDThh:mm:ss\&quot; format) (optional)
/// @param groupingWidth The time (in seconds) over which measurements are grouped together (optional)
/// @param groupingTimezone The time (in seconds) over which measurements are grouped together (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
/// @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGMeasurement*
-(NSNumber*) v1MeasurementsDailyGetWithVariableName: (NSString*) variableName
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    unitAbbreviatedName: (NSString*) unitAbbreviatedName
    startTime: (NSString*) startTime
    endTime: (NSString*) endTime
    groupingWidth: (NSNumber*) groupingWidth
    groupingTimezone: (NSString*) groupingTimezone
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSNumber*) sort
    completionHandler: (void (^)(SWGMeasurement* output, NSError* error)) handler;


/// Delete a measurement
/// Delete a previously submitted measurement
///
/// @param body The startTime and variableId of the measurement to be deleted.
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1MeasurementsDeletePostWithBody: (SWGMeasurementDelete*) body
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;


/// Get measurements for this user
/// Measurements are any value that can be recorded like daily steps, a mood rating, or apples eaten. Supported filter parameters:<ul><li><b>value</b> - Value of measurement</li><li><b>updatedAt</b> - The time that this measurement was created or last updated in the UTC format \"YYYY-MM-DDThh:mm:ss\"</li></ul>
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param _id Measurement id (optional)
/// @param variableName Name of the variable you want measurements for (optional)
/// @param variableCategoryName Name of the variable category you want measurements for (optional)
/// @param sourceName ID of the source you want measurements for (supports exact name match only) (optional)
/// @param value Value of measurement (optional)
/// @param unitAbbreviatedName The unit you want the measurements returned in (optional)
/// @param earliestMeasurementTime The lower limit of measurements returned in ISO 8601 format or epoch seconds (unixtime) (optional)
/// @param latestMeasurementTime The upper limit of measurements returned in ISO 8601 format or epoch seconds (unixtime) (optional)
/// @param createdAt The time the measurement record was first created in the format YYYY-MM-DDThh:mm:ss. Time zone should be UTC and not local. (optional)
/// @param updatedAt The time the measurement record was last changed in the format YYYY-MM-DDThh:mm:ss. Time zone should be UTC and not local. (optional)
/// @param groupingWidth The time (in seconds) over which measurements are grouped together (optional)
/// @param groupingTimezone The time (in seconds) over which measurements are grouped together (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
/// @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGMeasurement*
-(NSNumber*) v1MeasurementsGetWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    _id: (NSNumber*) _id
    variableName: (NSString*) variableName
    variableCategoryName: (NSString*) variableCategoryName
    sourceName: (NSString*) sourceName
    value: (NSString*) value
    unitAbbreviatedName: (NSString*) unitAbbreviatedName
    earliestMeasurementTime: (NSString*) earliestMeasurementTime
    latestMeasurementTime: (NSString*) latestMeasurementTime
    createdAt: (NSString*) createdAt
    updatedAt: (NSString*) updatedAt
    groupingWidth: (NSNumber*) groupingWidth
    groupingTimezone: (NSString*) groupingTimezone
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSNumber*) sort
    completionHandler: (void (^)(SWGMeasurement* output, NSError* error)) handler;


/// Post a new set or update existing measurements to the database
/// You can submit or update multiple measurements in a \"measurements\" sub-array.  If the variable these measurements correspond to does not already exist in the database, it will be automatically added.  The request body should look something like [{\"measurements\":[{\"startTime\":1439389320,\"value\":\"3\"}, {\"startTime\":1439389319,\"value\":\"2\"}],\"name\":\"Acne (out of 5)\",\"source\":\"QuantiModo\",\"category\":\"Symptoms\",\"combinationOperation\":\"MEAN\",\"unit\":\"/5\"}]
///
/// @param body An array of measurements you want to insert.
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Measurements successfully stored",
///  code:401 message:"Not Authenticated"
///
/// @return 
-(NSNumber*) v1MeasurementsPostWithBody: (SWGMeasurementSet*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSError* error)) handler;


/// Get measurements range for this user
/// Get Unix time-stamp (epoch time) of the user's first and last measurements taken.
///
/// @param sources Enter source name to limit to specific source (varchar) (optional)
/// @param user If not specified, uses currently logged in user (bigint) (optional)
/// 
///  code:200 message:"Successful operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGMeasurementRange*
-(NSNumber*) v1MeasurementsRangeGetWithSources: (NSString*) sources
    user: (NSNumber*) user
    completionHandler: (void (^)(SWGMeasurementRange* output, NSError* error)) handler;


/// Update a measurement
/// Delete a previously submitted measurement
///
/// @param body The id as well as the new startTime, note, and/or value of the measurement to be updated
/// 
///  code:201 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1MeasurementsUpdatePostWithBody: (SWGMeasurementUpdate*) body
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;


/// Get Measurements CSV
/// Download a CSV containing all user measurements
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return NSURL*
-(NSNumber*) v2MeasurementsCsvGetWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Post Request for Measurements CSV
/// Use this endpoint to schedule a CSV export containing all user measurements to be emailed to the user within 24 hours.
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return NSNumber*
-(NSNumber*) v2MeasurementsRequestCsvPostWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;


/// Post Request for Measurements PDF
/// Use this endpoint to schedule a PDF export containing all user measurements to be emailed to the user within 24 hours.
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return NSNumber*
-(NSNumber*) v2MeasurementsRequestPdfPostWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;


/// Post Request for Measurements XLS
/// Use this endpoint to schedule a XLS export containing all user measurements to be emailed to the user within 24 hours.
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return NSNumber*
-(NSNumber*) v2MeasurementsRequestXlsPostWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;



@end
