#import <Foundation/Foundation.h>
#import "SWGCommonResponse.h"
#import "SWGInlineResponse200.h"
#import "SWGInlineResponse2001.h"
#import "SWGInlineResponse2002.h"
#import "SWGTrackingReminder.h"
#import "SWGTrackingReminderDelete.h"
#import "SWGTrackingReminderNotificationSkip.h"
#import "SWGTrackingReminderNotificationSnooze.h"
#import "SWGTrackingReminderNotificationTrack.h"
#import "SWGApi.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGRemindersApi: NSObject <SWGApi>

extern NSString* kSWGRemindersApiErrorDomain;
extern NSInteger kSWGRemindersApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Get specific pending tracking reminders
/// Specfic pending reminder instances that still need to be tracked.  
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param variableCategoryName Limit tracking reminder notifications to a specific variable category (optional)
/// @param createdAt When the record was first created. Use UTC ISO 8601 \&quot;YYYY-MM-DDThh:mm:ss\&quot;  datetime format. Time zone should be UTC and not local. (optional)
/// @param updatedAt When the record was last updated. Use UTC ISO 8601 \&quot;YYYY-MM-DDThh:mm:ss\&quot;  datetime format. Time zone should be UTC and not local. (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. The maximum limit is 200 records. (optional)
/// @param offset OFFSET says to skip that many rows before beginning to return rows to the client. OFFSET 0 is the same as omitting the OFFSET clause. If both OFFSET and LIMIT appear, then OFFSET rows are skipped before starting to count the LIMIT rows that are returned. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#39;-&#39;, it will sort in descending order. (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return SWGInlineResponse2002*
-(NSNumber*) v1TrackingReminderNotificationsGetWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    variableCategoryName: (NSString*) variableCategoryName
    createdAt: (NSString*) createdAt
    updatedAt: (NSString*) updatedAt
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSString*) sort
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error)) handler;


/// Skip a pending tracking reminder
/// Deletes the pending tracking reminder
///
/// @param body Id of the pending reminder to be skipped or deleted
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1TrackingReminderNotificationsSkipPostWithBody: (SWGTrackingReminderNotificationSkip*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;


/// Snooze a pending tracking reminder
/// Changes the reminder time to now plus one hour
///
/// @param body Id of the pending reminder to be snoozed
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1TrackingReminderNotificationsSnoozePostWithBody: (SWGTrackingReminderNotificationSnooze*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;


/// Track a pending tracking reminder
/// Adds the default measurement for the pending tracking reminder with the reminder time as the measurment start time
///
/// @param body Id of the pending reminder to be tracked
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1TrackingReminderNotificationsTrackPostWithBody: (SWGTrackingReminderNotificationTrack*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;


/// Delete tracking reminder
/// Delete previously created tracking reminder
///
/// @param body Id of reminder to be deleted
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1TrackingRemindersDeletePostWithBody: (SWGTrackingReminderDelete*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;


/// Get repeating tracking reminder settings
/// Users can be reminded to track certain variables at a specified frequency with a default value.
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param variableCategoryName Limit tracking reminders to a specific variable category (optional)
/// @param createdAt When the record was first created. Use UTC ISO 8601 \&quot;YYYY-MM-DDThh:mm:ss\&quot;  datetime format. Time zone should be UTC and not local. (optional)
/// @param updatedAt When the record was last updated. Use UTC ISO 8601 \&quot;YYYY-MM-DDThh:mm:ss\&quot;  datetime format. Time zone should be UTC and not local. (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. The maximum limit is 200 records. (optional)
/// @param offset OFFSET says to skip that many rows before beginning to return rows to the client. OFFSET 0 is the same as omitting the OFFSET clause. If both OFFSET and LIMIT appear, then OFFSET rows are skipped before starting to count the LIMIT rows that are returned. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#39;-&#39;, it will sort in descending order. (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return SWGInlineResponse200*
-(NSNumber*) v1TrackingRemindersGetWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    variableCategoryName: (NSString*) variableCategoryName
    createdAt: (NSString*) createdAt
    updatedAt: (NSString*) updatedAt
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSString*) sort
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;


/// Store a Tracking Reminder
/// This is to enable users to create reminders to track a variable with a default value at a specified frequency
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param body TrackingReminder that should be stored (optional)
/// 
///  code:200 message:"successful operation"
///
/// @return SWGInlineResponse2001*
-(NSNumber*) v1TrackingRemindersPostWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    body: (SWGTrackingReminder*) body
    completionHandler: (void (^)(SWGInlineResponse2001* output, NSError* error)) handler;



@end
