#import <Foundation/Foundation.h>
#import "SWGCommonResponse.h"
#import "SWGUserTag.h"
#import "SWGApi.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGTagsApi: NSObject <SWGApi>

extern NSString* kSWGTagsApiErrorDomain;
extern NSInteger kSWGTagsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Delete user tag or ingredient
/// Delete previously created user tags or ingredients.
///
/// @param taggedVariableId This is the id of the variable being tagged with an ingredient or something.
/// @param tagVariableId This is the id of the ingredient variable whose value is determined based on the value of the tagged variable.
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1UserTagsDeletePostWithTaggedVariableId: (NSNumber*) taggedVariableId
    tagVariableId: (NSNumber*) tagVariableId
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;


/// Post or update user tags or ingredients
/// This endpoint allows users to tag foods with their ingredients.  This information will then be used to infer the user intake of the different ingredients by just entering the foods. The inferred intake levels will then be used to determine the effects of different nutrients on the user during analysis.
///
/// @param body Contains the new user tag data
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful Operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGCommonResponse*
-(NSNumber*) v1UserTagsPostWithBody: (SWGUserTag*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGCommonResponse* output, NSError* error)) handler;



@end
