#import <Foundation/Foundation.h>
#import "SWGUser.h"
#import "SWGUserTokenFailedResponse.h"
#import "SWGUserTokenRequest.h"
#import "SWGUserTokenSuccessfulResponse.h"
#import "SWGApi.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGUserApi: NSObject <SWGApi>

extern NSString* kSWGUserApiErrorDomain;
extern NSInteger kSWGUserApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Get user tokens for existing users, create new users
/// Get user tokens for existing users, create new users
///
/// @param organizationId Organization ID
/// @param body Provides organization token and user ID
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"User has been found, token was returned",
///  code:201 message:"User has been created, token was returned",
///  code:400 message:"Bad data",
///  code:403 message:"Forbidden"
///
/// @return SWGUserTokenSuccessfulResponse*
-(NSNumber*) v1OrganizationsOrganizationIdUsersPostWithOrganizationId: (NSNumber*) organizationId
    body: (SWGUserTokenRequest*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGUserTokenSuccessfulResponse* output, NSError* error)) handler;


/// Get all available units for variableGet authenticated user
/// Returns user info for the currently authenticated user.
///
/// 
///  code:200 message:"Successful operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGUser*
-(NSNumber*) v1UserMeGetWithCompletionHandler: 
    (void (^)(SWGUser* output, NSError* error)) handler;



@end
