#import <Foundation/Foundation.h>
#import "SWGUserVariableDelete.h"
#import "SWGUserVariables.h"
#import "SWGVariable.h"
#import "SWGVariableCategory.h"
#import "SWGVariablesNew.h"
#import "SWGApi.h"

/**
* QuantiModo
* QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGVariablesApi: NSObject <SWGApi>

extern NSString* kSWGVariablesApiErrorDomain;
extern NSInteger kSWGVariablesApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Get public variables
/// This endpoint retrieves an array of all public variables. Public variables are things like foods, medications, symptoms, conditions, and anything not unique to a particular user. For instance, a telephone number or name would not be a public variable.
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param _id Common variable id (optional)
/// @param category Filter data by category (optional)
/// @param name Original name of the variable (supports exact name match only) (optional)
/// @param updatedAt Filter by the last time any of the properties of the variable were changed. Uses UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot; (optional)
/// @param source The name of the data source that created the variable (supports exact name match only). So if you have a client application and you only want variables that were last updated by your app, you can include the name of your app here (optional)
/// @param latestMeasurementTime Filter variables based on the last time a measurement for them was created or updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot; (optional)
/// @param numberOfRawMeasurements Filter variables by the total number of measurements that they have. This could be used of you want to filter or sort by popularity. (optional)
/// @param lastSource Limit variables to those which measurements were last submitted by a specific source. So if you have a client application and you only want variables that were last updated by your app, you can include the name of your app here. (supports exact name match only) (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
/// @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
/// 
///  code:200 message:"Successful operation",
///  code:401 message:"Not Authenticated"
///
/// @return SWGVariable*
-(NSNumber*) v1PublicVariablesGetWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    _id: (NSNumber*) _id
    category: (NSString*) category
    name: (NSString*) name
    updatedAt: (NSString*) updatedAt
    source: (NSString*) source
    latestMeasurementTime: (NSString*) latestMeasurementTime
    numberOfRawMeasurements: (NSString*) numberOfRawMeasurements
    lastSource: (NSString*) lastSource
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSNumber*) sort
    completionHandler: (void (^)(SWGVariable* output, NSError* error)) handler;


/// Get top 5 PUBLIC variables with the most correlations
/// Get top 5 PUBLIC variables with the most correlations containing the entered search characters. For example, search for 'mood' as an effect. Since 'Overall Mood' has a lot of correlations with other variables, it should be in the autocomplete list.Supported filter parameters:<ul><li><b>category</b> - Category of Variable</li></ul>
///
/// @param search Search query can be some fraction of a variable name.
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param variableCategoryName Filter variables by category name. The variable categories include Activity, Causes of Illness, Cognitive Performance, Conditions, Environment, Foods, Location, Miscellaneous, Mood, Nutrition, Physical Activity, Physique, Sleep, Social Interactions, Symptoms, Treatments, Vital Signs, and Work. (optional)
/// @param source Specify a data source name to only return variables from a specific data source. (optional)
/// @param effectOrCause Indicate if you only want variables that have user correlations. Possible values are effect and cause. (optional)
/// @param publicEffectOrCause Indicate if you only want variables that have aggregated correlations.  Possible values are effect and cause. (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
/// @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
/// 
///  code:200 message:"Variables returned",
///  code:401 message:"Not Authenticated"
///
/// @return SWGVariable*
-(NSNumber*) v1PublicVariablesSearchSearchGetWithSearch: (NSString*) search
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    variableCategoryName: (NSString*) variableCategoryName
    source: (NSString*) source
    effectOrCause: (NSString*) effectOrCause
    publicEffectOrCause: (NSString*) publicEffectOrCause
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSNumber*) sort
    completionHandler: (void (^)(SWGVariable* output, NSError* error)) handler;


/// Delete All Measurements For Variable
/// Users can delete all of their measurements for a variable
///
/// @param variableId Id of the variable whose measurements should be deleted
/// 
///  code:200 message:"Successful operation",
///  code:400 message:"The received JSON was invalid or malformed",
///  code:401 message:"Not Authenticated",
///  code:404 message:"Unknown target user ID"
///
/// @return 
-(NSNumber*) v1UserVariablesDeletePostWithVariableId: (SWGUserVariableDelete*) variableId
    completionHandler: (void (^)(NSError* error)) handler;


/// Update User Settings for a Variable
/// Users can change the parameters used in analysis of that variable such as the expected duration of action for a variable to have an effect, the estimated delay before the onset of action. In order to filter out erroneous data, they are able to set the maximum and minimum reasonable daily values for a variable.
///
/// @param userVariables Variable user settings data
/// 
///  code:200 message:"Successful operation",
///  code:400 message:"The received JSON was invalid or malformed",
///  code:401 message:"Not Authenticated",
///  code:404 message:"Unknown target user ID"
///
/// @return 
-(NSNumber*) v1UserVariablesPostWithUserVariables: (SWGUserVariables*) userVariables
    completionHandler: (void (^)(NSError* error)) handler;


/// Reset user settings for a variable to defaults
/// Reset user settings for a variable to defaults
///
/// @param variableId Id of the variable that should be reset
/// 
///  code:201 message:"Successful operation",
///  code:400 message:"The received JSON was invalid or malformed",
///  code:401 message:"Not Authenticated",
///  code:404 message:"Unknown target user ID"
///
/// @return 
-(NSNumber*) v1UserVariablesResetPostWithVariableId: (SWGUserVariableDelete*) variableId
    completionHandler: (void (^)(NSError* error)) handler;


/// Variable categories
/// The variable categories include Activity, Causes of Illness, Cognitive Performance, Conditions, Environment, Foods, Location, Miscellaneous, Mood, Nutrition, Physical Activity, Physique, Sleep, Social Interactions, Symptoms, Treatments, Vital Signs, and Work.
///
/// 
///  code:200 message:"Successful operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGVariableCategory>*
-(NSNumber*) v1VariableCategoriesGetWithCompletionHandler: 
    (void (^)(NSArray<SWGVariableCategory>* output, NSError* error)) handler;


/// Get variables with user's settings
/// Get variables for which the user has measurements. If the user has specified variable settings, these are provided instead of the common variable defaults.
///
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param _id Common variable id (optional)
/// @param category Filter data by category (optional)
/// @param name Original name of the variable (supports exact name match only) (optional)
/// @param updatedAt Filter by the last time any of the properties of the variable were changed. Uses UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot; (optional)
/// @param source The name of the data source that created the variable (supports exact name match only). So if you have a client application and you only want variables that were last updated by your app, you can include the name of your app here (optional)
/// @param latestMeasurementTime Filter variables based on the last time a measurement for them was created or updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot; (optional)
/// @param numberOfRawMeasurements Filter variables by the total number of measurements that they have. This could be used of you want to filter or sort by popularity. (optional)
/// @param lastSource Limit variables to those which measurements were last submitted by a specific source. So if you have a client application and you only want variables that were last updated by your app, you can include the name of your app here. (supports exact name match only) (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
/// @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
/// @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order. (optional)
/// 
///  code:200 message:"Variables returned",
///  code:401 message:"Not Authenticated"
///
/// @return SWGVariable*
-(NSNumber*) v1VariablesGetWithAccessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    _id: (NSNumber*) _id
    category: (NSString*) category
    name: (NSString*) name
    updatedAt: (NSString*) updatedAt
    source: (NSString*) source
    latestMeasurementTime: (NSString*) latestMeasurementTime
    numberOfRawMeasurements: (NSString*) numberOfRawMeasurements
    lastSource: (NSString*) lastSource
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    sort: (NSNumber*) sort
    completionHandler: (void (^)(SWGVariable* output, NSError* error)) handler;


/// Create Variables
/// Allows the client to create a new variable in the `variables` table.
///
/// @param body Original name for the variable.
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Successful operation",
///  code:201 message:"Variable created",
///  code:401 message:"Not Authenticated"
///
/// @return 
-(NSNumber*) v1VariablesPostWithBody: (SWGVariablesNew*) body
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(NSError* error)) handler;


/// Get variables by search query
/// Get variables containing the search characters for which the currently logged in user has measurements. Used to provide auto-complete function in variable search boxes.
///
/// @param search Search query which may be an entire variable name or a fragment of one.
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// @param variableCategoryName Filter variables by category name. The variable categories include Activity, Causes of Illness, Cognitive Performance, Conditions, Environment, Foods, Location, Miscellaneous, Mood, Nutrition, Physical Activity, Physique, Sleep, Social Interactions, Symptoms, Treatments, Vital Signs, and Work. (optional)
/// @param includePublic Set to true if you would like to include public variables when no user variables are found. (optional)
/// @param manualTracking Set to true if you would like to exlude variables like apps and website names. (optional)
/// @param source Specify a data source name to only return variables from a specific data source. (optional)
/// @param effectOrCause Indicate if you only want variables that have user correlations. Possible values are effect and cause. (optional)
/// @param publicEffectOrCause Indicate if you only want variables that have aggregated correlations.  Possible values are effect and cause. (optional)
/// @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. (optional)
/// @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;. (optional)
/// 
///  code:200 message:"Successful operation",
///  code:401 message:"Not Authenticated"
///
/// @return NSArray<SWGVariable>*
-(NSNumber*) v1VariablesSearchSearchGetWithSearch: (NSString*) search
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    variableCategoryName: (NSString*) variableCategoryName
    includePublic: (NSNumber*) includePublic
    manualTracking: (NSNumber*) manualTracking
    source: (NSString*) source
    effectOrCause: (NSString*) effectOrCause
    publicEffectOrCause: (NSString*) publicEffectOrCause
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    completionHandler: (void (^)(NSArray<SWGVariable>* output, NSError* error)) handler;


/// Get info about a variable
/// Get all of the settings and information about a variable by its name. If the logged in user has modified the settings for the variable, these will be provided instead of the default settings for that variable.
///
/// @param variableName Variable name
/// @param accessToken User&#39;s OAuth2 access token (optional)
/// @param userId User&#39;s id (optional)
/// 
///  code:200 message:"Variables returned",
///  code:401 message:"Not Authenticated"
///
/// @return SWGVariable*
-(NSNumber*) v1VariablesVariableNameGetWithVariableName: (NSString*) variableName
    accessToken: (NSString*) accessToken
    userId: (NSNumber*) userId
    completionHandler: (void (^)(SWGVariable* output, NSError* error)) handler;



@end
